= ELK
:icons:
:toc:
:numbered:
:toclevels: 4
:source-highlighter: highlightjs
:highlightjsdir: highlight
:highlightjs-theme: monokai

:source-language: bash

（下文未特别说明的，运行环境为64位Linux）

== Elastic Search

=== ES安装、配置和运行

. Elastic Search 需要JDK（安装方法略）。

. 上传包文件(*.tar.gz)到服务器指定目录，然后解压缩文件包（以版本6.3.0为例）：
+
[source]
----
cd /usr/elastic
tar -zxvf elasticsearch-6.3.0.tar.gz
----

. 创建ES用户和组
+
为安全考虑，ES（v5.0+）不允许以root用户运行，需添加其他用户：
+
[source]
----
# 添加用户组
groupadd elsearch
# 在用户组中添加用户
useradd elsearch -g elsearch
# 修改密码
passwd elsearch
# 赋权限
chown -R elsearch:elsearch elasticsearch-6.3.0

# 添加单用户
adduser elsearch
# 修改密码
passwd elsearch
# 赋权限
chown -R elsearch elastic
----

. （可选）如果虚拟机内存小于2G，JVM可能报错“内存不足”，提示如下：
+
----
... error='Cannot allocate memory' (errno=12)
#
# There is insufficient memory for the Java Runtime Environment to continue.
----
+
使用以下命令修改默认配置（1G → 512M）：
+
----
vi /usr/elastic/elasticsearch-6.3.0/config/jvm.options
----
+
----
# -Xms1g
-Xms512m
# -Xmx1g
-Xmx512m
----

. 修改elasticsearch.yml配置文件

.. 打开yml文件：
+
[source]
----
cd /usr/elastic/elasticsearch-6.3.0/config
vi elasticsearch.yml
----

.. 取消如下注释，并修改为当前主机地址：
+
[source]
----
network.host: 192.168.40.128    # 改为0.0.0.0也可以
discovery.zen.ping.unicast.hosts: ["192.168.40.128"]
----

+
[NOTE]
.elasticsearch.yml 关键配置说明：
====
. cluster.name
+
集群名称，以此作为是否同一集群的判断条件。

. node.name
+
节点名称，以此作为集群中不同节点的区分条件。

. network.host/http.port
+
网络地址和端口，用于http和transport服务使用。

. path.data
+
数据存储地址。

. path.log
+
日志存储地址。
====

+
[TIP]
.参数修改的第二种方式：
====
bin/elasticsearch -Ehttp.port=19200
====

+
[NOTE]
.ES Development 与 Production 模式说明：
====
- 以transport（network.host）的地址是否绑定在localhost（或127.0.0.1）为判断标准，local的即为Development模式。
- Development模式下在启动时会以warning的方式提示配置检查异常。
- Production模式下在启动时会以error的方式提示配置检查异常并退出。
====


. 修改sysctl.conf配置文件

.. 打开conf文件：
+
[source]
----
vi /etc/sysctl.conf
----

.. 添加一行代码，防止报错：
+
[source]
----
vm.max_map_count=262144
----
+
附错误信息如下：
+
----
max virtual memory areas vm.max_map_count [65530] is too low,
increase to at least [262144]
----

.. 保存退出后重新加载：
+
[source]
----
sysctl -p
----

. 修改limits.conf配置文件

.. 打开conf文件：
+
[source]
----
vi /etc/security/limits.conf
----

.. 添加如下代码：
+
[source]
----
# 格式为：username|@groupname type resource limit
# type: soft 是当前生效的设置值，hard 是所能设定的最大值，soft 值不能比 hard 大，
#       用 - 表明同时设置 soft 和 hard 的值。

# elsearch soft nofile 65536
# elsearch hard nofile 65536
elsearch - nofile 65536

# elsearch soft nproc 4096
# elsearch hard nproc 4096
elsearch - nproc 4096
----
+
注意elsearch用户需要退出重新登录，所做的修改才能生效。

. 确认防火墙规则
+
如果防火墙关闭了相应端口，则ES只能在本机访问。临时测试时，（CentOS 7）可使用如下命令暂停防火墙服务：
+
[source]
----
systemctl stop firewalld
----
+
防火墙的进一步配置可参照命令：firewall-cmd
+
[source]
----
# 添加9200端口
firewall-cmd --permanent --zone=public --add-port=9200/tcp

# 重载防火墙
firewall-cmd --reload
----

. 进入es目录，以之前创建的ES用户运行程序（不能用root）：
+
[source]
----
# 切换用户
su elsearch
# 切换目录
cd /usr/elastic/elasticsearch-6.3.0/bin
# 前台运行ES
./elasticsearch
# 后台运行ES
./elasticsearch -d
----

. 验证结果
+
用浏览器访问服务器的9200端口（本机可以访问 127.0.0.1:9200），如果正常返回一段JSON数据，说明安装成功。

=== （后台）ES作业的查看和停止

. 查找进程，获取进程号
+
[source]
----
# 方法1
ps -ef | grep elastic

# 方法2
jps
----

. 终止进程
+
[source]
----
kill -9 nnnn    #nnnn为进程号
----

=== ES集群

. 本地启动集群的方式：
+
[source]
----
bin/elasticsearch
bin/elasticsearch -Ehttp.port=8200 -Epath.data=node2
bin/elasticsearch -Ehttp.port=7200 -Epath.data=node3
----

. 通过http查看ES相关信息的方法：
+
[source]
----
# 查看集群节点（标*号的是主节点）
127.0.0.1:8200/_cat/nodes?v

# 查看集群信息
127.0.0.1:8200/_cluster/stats
----

=== elasticsearch-sql 的安装和使用

项目地址： https://github.com/NLPchina/elasticsearch-sql

. 插件安装（针对 Elasticsearch 5.x/6.x）

.. 根据ElasticSearch的版本下载对应版本的zip包 ，上传到服务器，unzip。

.. 安装插件：
+
[source]
----
./bin/elasticsearch-plugin install file:///home/yourFolder/elasticsearch-sql-x.x.x.x.zip
----

.. 修改ES配置文件：
+
[source]
----
vi ./config/elasticsearch.yml
----
+
追加如下设定：
+
[source]
----
http.cors.enabled: true
# http.cors.allow-origin: "*"
http.cors.allow-origin: /https?:\/\/yourHost(:[0-9]+)?/
http.cors.allow-headers: "X-Requested-With, Content-Type, Content-Length, Authorization"
----

.. 重启ES，使新增设定生效。

. es-sql-site 的安装和运行（需要Node.js）

.. 下载 es-sql-site-standalone.zip ，unzip。
+
（注意该包并未和每个版本的 elasticsearch-sql 一同更新，在es-sql的发布中找最新的即可。）

.. 修改站点访问端口：
+
[source]
----
vim ./site-server/site_configuration.json
----

.. 安装web框架模块并运行站点：
+
[source]
----
cd site-server
npm install express --save
node node-server.js
----

.. 打开 http://yourHost:yourPort ，页面右上角的地址栏中填写 ES 的地址和端口。

=== es2csv

. 安装
+
[source]
----
yum -y install epel-release
yum install python-pip
pip install --upgrade pip
yum clean all
pip install es2csv

yum update
----

. 使用
+
[source]
----
# 测试连通
curl -XGET http://yourHost:yourPort
# 导出数据
es2csv -u http://yourHost:yourPort -i yourIndex -q '*' -o yourFile.csv
----

== Kibana

=== Kibana安装、配置和运行

. 上传包文件(*.tar.gz)到服务器指定目录，然后解压缩文件包（以版本6.3.0为例）：
+
[source]
----
cd /usr/elastic
tar -zxvf kibana-6.3.0-linux-x86_64.tar.gz
----

. 修改kibana.yml配置文件

.. 打开yml文件：
+
[source]
----
cd /usr/elastic/kibana-6.3.0-linux-x86_64/config
vi kibana.yml
----

.. 取消如下注释，并修改为当前主机地址：
+
[source]
----
# ES也在本机且仅本地测试时可以使用localhost不改，需要外网访问时改为0.0.0.0
server.host: "192.168.40.128"

elasticsearch.url: "http://192.168.40.128:9200"
----

. 确认防火墙规则
+
[source]
----
# 添加默认的5601端口
firewall-cmd --permanent --zone=public --add-port=5601/tcp

# 重载防火墙
firewall-cmd --reload
----

. 进入kibana目录，运行程序：
+
[source]
----
cd /usr/elastic/kibana-6.3.0-linux-x86_64/
bin/kibana
----

. 验证结果
+
用浏览器访问服务器的5601端口。

=== Kibana使用入门

. CRUD
+
打开【Dev Tools】，使用如下脚本进行简单的CRUD测试：
+
[source]
----
POST /accounts/person/1
{
  "name": "John",
  "lastname": "Doe",
  "job_description": "Systems administrator and Linux specialist"
}

GET accounts/person/1

POST /accounts/person/1/_update
{
  "doc":{
    "job_description": "Systems administrator and Linux specialist * "
  }
}

DELETE accounts/person/1
----

. 两种查询方法
+
[source]
----
// Query String
GET /accounts/person/_search?q=john

// Query DSL 1
GET accounts/person/_search
{
  "query": {
    "match": {
      "name": "john"
    }
  }
}

// Query DSL 2
GET accounts/person/_search
{
  "query": {
    "term": {
      "name": {
        "value": "john"
      }
    }
  }
}
----

