= ELK
:icons:
:toc:
:numbered:
:toclevels: 4
:source-highlighter: highlightjs
:highlightjsdir: highlight
:highlightjs-theme: monokai

:source-language: bash

（下文未特别说明的，运行环境为64位Linux）

== Elastic Search

Elastic Search 需要JDK，安装方法此处略去。

=== ES安装、配置和运行

. 上传包文件(*.tar.gz)到服务器指定目录，然后解压缩文件包（以版本6.3.0为例）：
+
[source]
----
cd /usr/elastic
tar -zxvf elasticsearch-6.3.0.tar.gz
----

. 修改elasticsearch.yml配置文件

.. 打开yml文件：
+
[source]
----
cd /usr/elastic/elasticsearch-6.3.0/config
vim elasticsearch.yml
----

.. 取消如下注释，并修改为当前主机地址：
+
[source]
----
network.host: 192.168.40.128    # 改为0.0.0.0也可以
discovery.zen.ping.unicast.hosts: ["192.168.40.128"]
----

+
[NOTE]
.elasticsearch.yml 关键配置说明：
====
. cluster.name
+
集群名称，以此作为是否同一集群的判断条件。

. node.name
+
节点名称，以此作为集群中不同节点的区分条件。

. network.host/http.port
+
网络地址和端口，用于http和transport服务使用。

. path.data
+
数据存储地址。

. path.log
+
日志存储地址。
====

+
[TIP]
.参数修改的第二种方式：
====
bin/elasticsearch -Ehttp.port=19200
====

+
[NOTE]
.ES Development 与 Production 模式说明：
====
- 以transport（network.host）的地址是否绑定在localhost（或127.0.0.1）为判断标准，local的即为Development模式。
- Development模式下在启动时会以warning的方式提示配置检查异常。
- Production模式下在启动时会以error的方式提示配置检查异常并退出。
====


. 修改sysctl.conf配置文件

.. 打开conf文件：
+
[source]
----
vim /etc/sysctl.conf
----

.. 添加一行代码：
+
[source]
----
vm.max_map_count=262144
----

.. 保存退出后重新加载：
+
[source]
----
sysctl -p
----

. 修改limits.conf配置文件

.. 打开conf文件：
+
[source]
----
vim /etc/security/limits.conf
----

.. 添加如下代码：
+
[source]
----
# esuser01为登录服务器的用户名
esuser01 soft nofile 65536
esuser01 hard nofile 65536
esuser01 soft nproc 4096
esuser01 hard nproc 4096
----
+
注意esuser01用户需要退出重新登录，所做的修改才能生效。

. 确认防火墙规则
+
如果防火墙关闭了相应端口，则ES只能在本机访问。临时测试时，（CentOS 7）可使用如下命令暂停防火墙服务：
+
[source]
----
systemctl stop firewalld
----
+
防火墙的进一步配置可参照命令：firewall-cmd
+
[source]
----
# 添加9200端口
firewall-cmd --permanent --zone=public --add-port=9200/tcp

# 重载防火墙
firewall-cmd --reload
----

. 进入es目录，运行程序：
+
[source]
----
cd /usr/elastic/elasticsearch-6.3.0/
bin/elasticsearch   <1>
----
+
[NOTE]
====
<1> 为了安全考虑，ES不允许以root用户运行，可以添加其他用户来运行。
+
[source]
----
# 添加用户
adduser esuser01
# 修改密码
passwd esuser01

# 赋权限
chown -R esuser01 elastic

# 切换用户，然后运行es
su esuser01
cd elastic/elasticsearch-6.3.0/bin
./elasticsearch
----
====

. 验证结果
+
用浏览器访问服务器的9200端口（本机可以访问 127.0.0.1:9200），如果正常返回一段JSON数据，说明安装成功。

=== ES集群

. 本地启动集群的方式：
+
[source]
----
bin/elasticsearch
bin/elasticsearch -Ehttp.port=8200 -Epath.data=node2
bin/elasticsearch -Ehttp.port=7200 -Epath.data=node3
----

. 通过http查看ES相关信息的方法：
+
[source]
----
# 查看集群节点（标*号的是主节点）
127.0.0.1:8200/_cat/nodes?v

# 查看集群信息
127.0.0.1:8200/_cluster/stats
----

== Kibana

=== Kibana安装、配置和运行

. 上传包文件(*.tar.gz)到服务器指定目录，然后解压缩文件包（以版本6.3.0为例）：
+
[source]
----
cd /usr/elastic
tar -zxvf kibana-6.3.0-linux-x86_64.tar.gz
----

. 修改kibana.yml配置文件

.. 打开yml文件：
+
[source]
----
cd /usr/elastic/kibana-6.3.0-linux-x86_64/config
vim kibana.yml
----

.. 取消如下注释，并修改为当前主机地址：
+
[source]
----
server.host: "192.168.40.128"
elasticsearch.url: "http://192.168.40.128:9200"
----

. 确认防火墙规则
+
[source]
----
# 添加默认的5601端口
firewall-cmd --permanent --zone=public --add-port=5601/tcp

# 重载防火墙
firewall-cmd --reload
----

. 进入kibana目录，运行程序：
+
[source]
----
cd /usr/elastic/kibana-6.3.0-linux-x86_64/
bin/kibana
----

. 验证结果
+
用浏览器访问服务器的5601端口。