= JavaScript
:icons:
:toc:
:toclevels: 4
:numbered:

== 基础（JavaScript高级程序设计 第3版）

=== JavaScript 元素

==== <Script>

. 属性

.. async 可选

.. charset 可选

.. defer 可选
+
立即下载、延迟执行，此属性的用途是表明脚本在执行时不会影响页面的构造。

.. language 已废弃
.. src 可选

.. type 可选
+
已不推荐使用，但考虑到约定俗成和最大限度的浏览器兼容性，可以设为 text/javascript（默认值）。

. 在使用 <script> 嵌入 JavaScript 代码时，不要在代码中的任何地方出现"</script>"字符串。
+
[source, html, numbered]
----
<script type="text/javascript">
    function sayScript(){
        alert("</script>");     //错误
        alert("<\/script>");    //正确
    }
</script>
----

. 如果是在 XHTML 文档中，可以省略 </script> 标签，例如：
+
[source, html, numbered]
----
<script type="text/javascript" src="example.js" />
----
+
但是，不能在 HTML 文档使用这种语法。原因是这种语法不符合 HTML 规范，而且也得不到某些浏览器（尤其是IE）的正确解析。
+
[NOTE]
======
- 按惯例，外部 JavaScript 文件带有 .js 扩展名，但这个扩展名不是必需的。
- 如果不使用 .js 扩展名，请确保服务器能返回正确的 MIME 类型。
======

. 带有 src 属性的 <script> 元素不应再包含额外代码。如果包含了，嵌入代码会被忽略，只有外部脚本文件会被下载并执行。

. 只要不存在 defer 和 async 属性，浏览器都会按照<script>元素在页面中出现的先后顺序对它们依次进行解析。换句话说，
  在第一个 <script> 元素包含的代码解析完成后，第二个 <script> 包含的代码才会被解析，然后才是第三个、第四个……

. 按照传统做法，所有 <script> 元素都应该放在页面的 <head> 元素中。
  这种做法的目的就是把所有外部文件（包括 CSS 文件和 JavaScript 文件）的引用都放在相同的地方。
  对于那些需要很多 JavaScript 代码的页面来说，这会导致浏览器在呈现页面时出现明显的延迟（浏览器在遇到 <body> 标签时才开始呈现内容）。
  为了避免这个问题，现代 Web 应用程序一般都把全部 JavaScript 引用放在 <body> 元素中页面内容的后面：
+
[source, html, numbered]
----
<!DOCTYPE html>
<html>
<head>
    <title>Example HTML Page</title>
</head>
<body>
<!-- 这里放内容 -->
<script type="text/javascript" src="example1.js"></script>
<script type="text/javascript" src="example2.js"></script>
</body>
</html>
----

. 延迟脚本
+
[source, html, numbered]
----
<!DOCTYPE html>
<html>
<head>
    <title>Example HTML Page</title>
    <script type="text/javascript" defer="defer" src="example1.js"></script>
    <script type="text/javascript" defer="defer" src="example2.js"></script>
</head>
<body>
<!-- 这里放内容 -->
</body>
</html>
----

.. HTML5 规范要求脚本按照它们出现的先后顺序执行，因此第一个延迟脚本会先于第二个执行，而这两个脚本会先于 DOMContentLoaded 事件执行。
.. 在现实当中，延迟脚本并不一定会按照顺序执行，也不一定会在 DOMContentLoaded 事件触发前执行，因此最好只包含一个延迟脚本。
.. defer 属性只适用于外部脚本文件。这一点在 HTML5 中已经明确规定，因此支持 HTML5 的实现会忽略给嵌入脚本设置的 defer 属性。
   IE4～IE7 还支持对嵌入脚本的 defer 属性，但 IE8 及之后版本则完全支持 HTML5 规定的行为。

. 异步脚本
+
[source, html, numbered]
----
<!DOCTYPE html>
<html>
<head>
    <title>Example HTML Page</title>
    <script type="text/javascript" async src="example1.js"></script>
    <script type="text/javascript" async src="example2.js"></script>
</head>
<body>
<!-- 这里放内容 -->
</body>
</html>
----

.. 与defer 类似，async 只适用于外部脚本文件，并立即下载文件。但与defer不同，标记为 async 的脚本并不保证按照指定它们的先后顺序执行。
.. 确保两脚本之间互不依赖非常重要。
.. 指定 async 属性的目的是不让页面等待脚本下载和执行，从而异步加载页面其他内容。为此，建议异步脚本不要在加载期间修改DOM。
.. 异步脚本一定会在页面的 load 事件前执行，但可能会在DOMContentLoaded 事件触发之前或之后执行。

. 文档模式
.. 混杂模式（quirks mode）

.. 标准模式（standards mode）
+
[source, html, numbered]
----
<!-- HTML 4.01 严格型 -->
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
        "http://www.w3.org/TR/html4/strict.dtd">

<!-- XHTML 1.0 严格型 -->
<!DOCTYPE html PUBLIC
        "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<!-- HTML 5 -->
<!DOCTYPE html>
----

.. 准标准模式（almost standards mode）
+
准标准模式与标准模式非常接近，它们的差异几乎可以忽略不计。
+
[source, html, numbered]
----
<!-- HTML 4.01 过渡型 -->
<!DOCTYPE HTML PUBLIC
        "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">

<!-- HTML 4.01 框架集型 -->
<!DOCTYPE HTML PUBLIC
        "-//W3C//DTD HTML 4.01 Frameset//EN"
        "http://www.w3.org/TR/html4/frameset.dtd">

<!-- XHTML 1.0 过渡型 -->
<!DOCTYPE html PUBLIC
        "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<!-- XHTML 1.0 框架集型 -->
<!DOCTYPE html PUBLIC
        "-//W3C//DTD XHTML 1.0 Frameset//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-frameset.dtd">
----

==== <NoScript>

. 举例
+
[source, html, numbered]
----
<html>
<head>
    <title>Example HTML Page</title>
    <script type="text/javascript" defer="defer" src="example1.js"></script>
    <script type="text/javascript" defer="defer" src="example2.js"></script>
</head>
<body>
<noscript>
    <p>本页面需要浏览器支持（启用）JavaScript。
</noscript>
</body>
</html>
----

=== 关键字和保留字

. ECMA-262 全部关键字（第5版新增的以*号标出）
+
[source, ecmascript, numbered]
----
break     do       instanceof typeof
case      else     new        var
catch     finally  return     void
continue  for      switch     while
debugger* function this       with
default   if       throw
delete    in       try
----

. ECMA-262 第3版全部保留字
+
[source, ecmascript, numbered]
----
abstract enum       int       short
boolean  export     interface static
byte     extends    long      super
char     final      native    synchronized
class    float      package   throws
const    goto       private   transient
debugger implements protected volatile
double   import     public
----

. ECMA-262 第5版，【非】严格模式保留字
+
[source, ecmascript, numbered]
----
class enum   extends super
const export import
----
+
严格模式还有以下保留字
+
[source, ecmascript, numbered]
----
implements package   public
interface  private   static
let*       protected yield*
----
+
另外还有以下受到限制，严格模式下，不能作为标识符或属性名
+
[source, ecmascript, numbered]
----
arguments eval
----

=== 变量

. 用 var 操作符定义的变量将成为定义该变量的作用域中的局部变量。
. 省略 var 操作符的，就成了全局变量。（但不推荐，严格模式下将报错。）

=== 数据类型

. ECMAScript 中有5种简单（/基本）数据类型：Undefined、Null、Boolean、Number和String，1种复杂数据类型：Object。

. typeof 是一个操作符而不是函数，返回值：undefined, boolean, string, number, object, function
+
[source, javascript, numbered]
----
alert(typeof(null));    //object
----

==== Undefined 类型

[source, javascript, numbered]
----
var message;
alert(message == undefined);    //true
----

未初始化的变量（默认值为"undefined"）和初始化为"undefined"的变量还是略有区别：

[source, javascript, numbered]
----
var message;    //变量声明后默认取得 undefined 值
alert(message); //undefined
alert(age);     //产生错误
----

==== Null 类型

[source, javascript, numbered]
----
alert(null == null);    //true

// undefined 值派生自 null 值，因此 ECMA-262 规定对它们的相等性测试要返回true
alert(null == undefined);   //true
----

==== Boolean 类型

. Boolean 类型的字面值 true 和 false 区分大小写，True 和 False 都不是 Boolean 值，只是标识符。

. Boolean()转型函数：
+
[cols="<,<,<", options="header,autowidth"]
|====
|数据类型 |转换为true的值 |转换为false的值
|Boolean |true |false
|String |任何非空字符串 |""（空字符串）
|Number |任何非零数字值（包括无穷大） |0和NaN
|Object |任何对象 |null
|Undefined |n/a（not applicable） |undefined
|====

==== Number 类型

. 八进制数值
+
第一位必须是零（0），在严格模式下无效：
+
[source, javascript, numbered]
----
var octalNum1 = 070;    // 八进制的56
var octalNum2 = 079;    // 无效的八进制数值——解析为79
----

. 十六进制数值
+
前两位必须是0x，字母 A～F 可以大写，也可以小写

. 进行算术计算时，所有以八进制和十六进制表示的数值最终都将被转换成十进制数值。
+
[NOTE]
====
JavaScript 中，可以保存正零（+0）和负零（-0），正零和负零被认为相等。
====

. 浮点数值

.. 基本写法：
+
[source, javascript, numbered]
----
var floatNum2 = 0.1;
var floatNum3 = .1;     //有效，但不推荐
----

.. ECMAScript 会不失时机地将浮点数值转换为整数值：
+
[source, javascript, numbered]
----
var floatNum1 = 1.;     //小数点后面没有数字——解析为1
var floatNum2 = 10.0;   //整数——解析为10
----

.. 默认情况下，ECMASctipt 会将小数点后面带有6个零及以上的浮点数值转换为以 e 表示法表示的数值（例如，0.0000003 会被转换成 3e-7）。

.. 浮点数值的最高精度是17位小数，但在进行算术计算时其精确度远远不如整数。例如，0.1 加 0.2 的结果不是 0.3，而是0.30000000000000004。
    这个小小的舍入误差会导致无法测试特定的浮点数值。
+
[source, javascript, numbered]
----
var a = 0.1;
var b = 0.2;
if (a + b == 0.3) { //不要做这样的测试！
  alert('You got 0.3.');
}
----
+
[NOTE]
====
关于浮点数值计算会产生舍入误差的问题，这是使用基于 IEEE754 数值的浮点计算的通病，ECMAScript 并非独此一家；
其他使用相同数值格式的语言也存在这个问题。
====

. 数值范围

.. ECMAScript 能够表示的最小数值保存在 Number.MIN_VALUE 中，最大数值保存在 Number.MAX_VALUE 中。

.. 如果某次计算的结果得到了一个超出 JavaScript 数值范围的值，那么这个数值将被自动转换成特殊的 Infinity 值。
    负数为 -Infinity（负无穷），正数为 Infinity（正无穷）。该值将无法继续参与下一次的计算。可以使用 isFinite() 函数进行检测。

. NaN

.. NaN，即非数值（Not a Number）是一个特殊的数值，用于表示一个本来要返回数值的操作数未返回数值的情况。例如 0 除以 0 将返回 NaN 。

.. 任何涉及 NaN 的操作（例如 NaN/10）都会返回NaN。

.. NaN 与任何值都不相等，包括 NaN 本身。
+
[source, javascript, numbered]
----
alert(NaN == NaN);      //false
----

.. isNaN()
+
[source, javascript, numbered]
----
alert(isNaN(NaN));  //true
alert(isNaN(10));   //false（10 是一个数值）
alert(isNaN("10")); //false（可以被转换成数值10）
alert(isNaN("blue"));   //true（不能转换成数值）
alert(isNaN(true)); //false（可以被转换成数值1）
----
+
[NOTE]
====
- isNaN() 也适用于对象，在基于对象调用isNaN() 函数时，会首先调用对象的 valueOf()方法，然后确定该方法返回的值是否可以转换为数值。
- 如果不能，则基于这个返回值再调用 toString() 方法，再测试返回值。
====

. 数值转换
+
有3个函数可以把非数值转换为数值：Number()、parseInt() 和 parseFloat()。

.. Number()
+
[source, javascript, numbered]
----
var num1 = Number("Hello world!");  //NaN
var num2 = Number("");  //0
var num3 = Number("000011");    //11
var num4 = Number(true);    //1
----

... true 和 false 将分别被转换为 1 和 0。

... null 值返回 0。

... undefined 值返回 NaN。

... 字符串遵循以下规则：
.... 字符串中只包含数字（包括带正号或负号的情况），则将其转换为十进制数值（忽略前导0）。
.... 字符串中包含有效的浮点格式，则将其转换为对应的浮点数值（忽略前导0）。
.... 字符串中包含有效的十六进制格式，则将其转换为相同大小的十进制整数值。
.... 字符串是空的（不包含任何字符），则将其转换为0。
.... 字符串中包含除上述格式之外的字符，则将其转换为 NaN。

... 如果是对象，则调用对象的 valueOf() 方法，然后进行转换。
     如果转换的结果是 NaN ，则调用对象的 toString() 方法，然后再次转换。

.. parseInt()
+
[source, javascript, numbered]
----
var num1 = parseInt("1234blue");    //1234
var num2 = parseInt("");    //NaN
var num3 = parseInt("0xA"); //10
var num4 = parseInt(22.5);  //22
var num5 = parseInt("70");  //70
var num6 = parseInt("070"); //ECMAScript 3 是56，ECMAScript 5 是70
----
+
为了消除 ECMAScript 3 和 5 的分歧，可以提供第2个参数：
+
[source, javascript, numbered]
----
var num1 = parseInt("0xAF", 16); //175
var num2 = parseInt("AF", 16);  //175
var num3 = parseInt("AF");      //NaN

var num4 = parseInt("10", 2);   //2 （按二进制解析）
var num5 = parseInt("10", 8);   //8 （按八进制解析）
var num6 = parseInt("10", 10);  //10 （按十进制解析）
var num7 = parseInt("10", 16);  //16 （按十六进制解析）
----

.. parseFloat()
+
[source, javascript, numbered]
----
var num1 = parseFloat("1234blue");  //1234（整数）
var num2 = parseFloat("0xA");       //0
var num3 = parseFloat("22.5");      //22.5
var num4 = parseFloat("22.34.5");   //22.34
var num5 = parseFloat("0908.5");    //908.5
var num6 = parseFloat("3.125e7");   //31250000
----

... 只解析十进制值，没有用第二个参数指定基数的用法。十六进制格式的字符串始终会被转换成0。
... 如果字符串包含的是一个可解析为整数的数（没有小数点，或者小数点后都是零），parseFloat()会返回整数。

==== String 类型

. 字符字面量
+
[cols="<,<", options="header,autowidth"]
|====
|字面量 |含义
|\n |换行
|\t |制表
|\b |空格
|\r |回车
|\f |进纸
|\\ |斜杠
|\' |单引号（'），在用单引号表示的字符串中使用。例如：'He said, \'hey.\''
|\" |双引号（"），在用双引号表示的字符串中使用。例如："He said, \"hey.\""
|\xnn |以十六进制代码nn表示的一个字符（其中n为0～F）。例如，\x41表示"A"
|\unnnn |以十六进制代码nnnn表示的一个Unicode字符（其中n为0～F）。例如，\u03a3表示希腊字符Σ
|====

. 任何字符串的长度都可以通过访问其 length 属性取得，如果字符串中包含双字节字符，那么 length 属性可能不会精确地返回字符串中的字符数目。

. ECMAScript 中的字符串一旦创建，它们的值就不能被改变。

. 除了 null 和 undefined 值外，数值、布尔值、对象和字符串值都有 toString() 方法。
   多数情况下，调用toString()方法不必传递参数。但是，可以传递一个参数来指定输出数值的基数。
+
[source, javascript, numbered]
----
var num = 10;
alert(num.toString());      //"10"
alert(num.toString(2));     //"1010"
alert(num.toString(8));     //"12"
alert(num.toString(10));    //"10"
alert(num.toString(16));    //"a"
----

. String()

.. 如果值有 toString() 方法，则调用该方法（没有参数）并返回相应的结果；
.. 如果值是 null，则返回"null"；
.. 如果值是 undefined，则返回"undefined"。

==== Object 类型

Object 的每个实例都具有下列属性和方法：

. constructor
+
保存着用于创建当前对象的函数。

. hasOwnProperty(propertyName)
+
用于检查给定的属性在当前对象实例中（而不是在实例的原型中）是否存在。
其中，作为参数的属性名（propertyName）必须以字符串形式指定。

. isPrototypeOf(object)
+
用于检查传入的对象是否是传入对象的原型。

. propertyIsEnumerable(propertyName)
+
用于检查给定的属性是否能够使用 for-in 语句来枚举。与hasOwnProperty()方法一样，作为参数的属性名必须以字符串形式指定。

. toLocaleString()
+
返回对象的字符串表示，该字符串与执行环境的地区对应。

. toString()
+
返回对象的字符串表示。

. valueOf()
+
返回对象的字符串、数值或布尔值表示。通常与toString()方法的返回值相同。

=== 操作符

==== 一元操作符

[source, javascript, numbered]
----
 ++
 --
 +
 -
----

==== 位操作符

. ECMAScript 中的所有数值都以 IEEE-754 64 位格式存储，但位操作符并不直接操作 64 位的值。
  而是先将 64 位的值转换成 32 位的整数，然后执行操作，最后再将结果转回 64 位。

. 对于有符号整数，32 位中的前 31 位（从右向左）用于表示整数的值。
  第一位（位0）表示 2^0^，第二位表示 2^1^，以此类推。
  第32位用于表示数值的符号：0 表示正数，1 表示负数。这个表示符号的位叫做符号位，符号位的值决定了其他位数值的格式。
  其中，正数以纯二进制格式存储，31 位中的每一位都表示 2 的幂。负数同样以二进制码存储，但使用的格式是二进制补码。
+
[NOTE]
.求二进制补码的三个步骤：
=====
. 求绝对值的二进制码；
. 求二进制反码，即将0替换为1，将1替换为0；
. 反码加1。
=====

. 对特殊的 NaN 和 Infinity 值应用位操作时，这两个值都会被当成 0 来处理。

. 按位非（NOT）
+
由一个波浪线（~）表示，返回数值的反码。（按位非操作的本质：操作数的负值减1。）

. 按位与（AND）
+
由一个和号字符（&）表示。

. 按位或（OR）
+
由一个竖线符号（|）表示。

. 按位异或（XOR）
+
由一个插入符号（^）表示，按位相同得0、不同得1。

. 左移
+
由两个小于号（<<）表示，左移不会影响操作数的符号位。

. 有符号的右移
+
由两个大于号（>>）表示，保留符号位，有符号的右移操作与左移操作恰好相反。

. 无符号的右移
+
由3个大于号（>>>）表示，会将数值的所有 32 位都向右移动。

==== 布尔操作符

. 逻辑非（NOT）
+
由一个叹号（!）表示：
+
[cols="<,<", options="header,autowidth"]
|====
|操作数 |返回
|对象（=> true） |false
|空字符串（=> false) |true
|非空字符串（=> true） |false
|数值0 |true
|非0数值（包括 Infinity） |false
|null, NaN, undefined |true
|====

. 逻辑与（AND）
+
由两个和号（&&）表示。

.. 可以应用于任何类型，在有一个操作数不是布尔值的情况下，遵循下列规则：
... 第1个操作数是对象，返回第2个操作数；
... 第2个操作数是对象，仅在第1个操作数的求值结果为true时才会返回该对象；
... 如果两个操作数都是对象，返回第2个操作数；
... 如果有一个操作数是null，返回null；
... 如果有一个操作数是NaN，返回NaN；
... 如果有一个操作数是undefined，返回undefined。

.. 属于短路操作，即如果第一个操作数能够决定结果，就不会再对第二个操作数求值。
+
[source, javascript, numbered]
----
var found = true;
var result = (found && someUndefinedVariable);  //发生错误
alert(result);  //不会执行
----
+
[source, javascript, numbered]
----
var found = false;
var result = (found && someUndefinedVariable); //不发生错误
alert(result);  //false
----

. 逻辑或（OR）
+
由两个竖线符号（||）表示。

.. 在有一个操作数不是布尔值的情况下，遵循下列规则：
... 如果第1个操作数是对象，返回第1个操作数；
... 如果第1个操作数的求值结果为false，返回第2个操作数；
... 如果两个操作数都是对象，返回第1个操作数；
... 如果两个操作数都是null，返回null；
... 如果两个操作数都是NaN，返回NaN；
... 如果两个操作数都是undefined，返回undefined。

.. 也属于短路操作，可以利用它来避免为变量赋 null 或 undefined 值。例如：
+
[source, javascript, numbered]
----
var myObject = preferredObject || backupObject;
----

==== 乘性操作符

. 乘法

.. 处理特殊值的规则如下：
... 如果有一个操作数是 NaN，结果是 NaN；
... Infinity * 0，结果是 NaN；
... Infinity * 非0数值，结果是 Infinity 或 -Infinity，取决于有符号操作数的符号；
... Infinity * Infinity 相乘，结果是 Infinity；
... 如果有一个操作数不是数值，则在后台调用Number()将其转换为数值，然后再应用上面的规则。

. 除法

.. 处理特殊值的规则如下：
... 如果有一个操作数是 NaN，结果是 NaN；
... Infinity / Infinity，结果是 NaN；
... 0 / 0，结果是 NaN；
... 非0的有限数 / 0，结果是 Infinity 或 -Infinity，取决于有符号操作数的符号；
... Infinity / 非0数值，则结果是 Infinity 或 -Infinity，取决于有符号操作数的符号；
... 如果有一个操作数不是数值，则在后台调用Number()将其转换为数值，然后再应用上面的规则。

. 求模（余数）
+
由一个百分号（%）表示。

.. 处理特殊值的规则如下：
... 有限大的数值 % 0，结果是 NaN；
... Infinity % Infinity，结果是 NaN；
... Infinity % 有限大的数值，结果是 NaN；
... 有限大的数值 % Infinity，结果是被除数；
... 如果被除数是0，则结果是0；
... 如果有一个操作数不是数值，则在后台调用Number()将其转换为数值，然后再应用上面的规则。

==== 加性操作符

. 加法

.. 处理特殊值的规则如下：
... 如果有一个操作数是 NaN，结果是 NaN；
... Infinity + Infinity，结果是 Infinity；
... (-Infinity) + (-Infinity)，结果是 -Infinity；
... Infinity + (-Infinity)，结果是 NaN；
... (+0) + (+0)，结果是 +0；
... (-0) + (-0)，结果是 -0；
... (+0) + (-0)，结果是 +0。

.. 如果有一个操作数是字符串，则进行字符串拼接。
... 如果另一个操作数是对象、数值或布尔值，则调用toString()取得相应字符串值，再进行拼接。
... 对于 undefined 和 null，则分别调用String()函数取得字符串 "undefined" 和 "null" ，再进行拼接。

.. 举例
+
[source, javascript, numbered]
----
var num1 = 5;
var num2 = 10;

var message1 = "The sum of 5 and 10 is " + num1 + num2;
alert(message1); // "The sum of 5 and 10 is 510"

var message2 = "The sum of 5 and 10 is " + (num1 + num2);
alert(message2); //"The sum of 5 and 10 is 15"
----

. 减法

.. 处理特殊值的规则如下：
... 如果有一个操作数是 NaN，结果是 NaN；
... Infinity - Infinity，结果是 NaN；
... (-Infinity) - (-Infinity)，结果是 NaN；
... Infinity - (-Infinity)，结果是 Infinity；
... (-Infinity) - Infinity，结果是 -Infinity；
... (+0) - (+0)，结果是 +0；
... (+0) - (-0)，结果是 -0；
... (-0) - (-0)，结果是 +0；

.. 如果有一个操作数是字符串、布尔值、null 或 undefined，则调用Number()函数将其转换为数值，然后再计算。
   如果转换的结果是 NaN，结果就是 NaN；

.. 如果有一个操作数是对象，则调用valueOf()方法以取得表示该对象的数值。
   如果得到的值是 NaN，结果就是NaN。
   如果对象没有valueOf()方法，则调用toString()方法并将得到的字符串转换为数值。

.. 举例
+
[source, javascript, numbered]
----
var result1 = 5 - true; //5 - 1 = 4
var result2 = 5 - "";   //5 - 0 = 5
var result3 = 5 - null; //5 - 0 = 5
----

==== 关系操作符

. 当关系操作符的操作数使用了非数值时，处理规则如下：

.. 如果两个操作数都是字符串，则比较两个字符串对应的字符编码值。

.. 如果一个操作数是数值，则将另一个操作数转换为一个数值，然后执行数值比较。
+
[source, javascript, numbered]
----
var result = "23" < 3;  //false

var result = "a" < 3;   //false，因为"a"被转换成了NaN

var result1 = NaN < 3;  //false
var result2 = NaN >= 3; //false
----

.. 如果一个操作数是对象，则调用这个对象的valueOf()方法，用得到的结果按照前面的规则执行比较。
   如果对象没有valueOf()方法，则调用toString()方法，并用得到的结果根据前面的规则执行比较。

.. 如果一个操作数是布尔值，则先将其转换为数值，然后再执行比较。

==== 相等操作符

. 相等（==）和不相等（!=）

.. 先转换再比较

.. 转换规则如下：
... 如果有一个操作数是布尔值，比较相等性之前先将其转换为数值——false 转换为0，true 转换为1；
... 如果一个操作数是字符串，另一个操作数是数值，在比较相等性之前先将字符串转换为数值；
... 如果一个操作数是对象，另一个操作数不是，则调用对象的valueOf()方法，用得到的基本类型值按照前面的规则进行比较.

.. 比较规则如下：
... null 和 undefined 是相等的。
... 要比较相等性之前，不能将 null 和 undefined 转换成其他任何值。
... 如果有一个操作数是 NaN，则相等操作符返回 false，而不相等操作符返回 true。
+
[NOTE]
=====
即使两个操作数都是NaN，相等操作符也返回false；因为按照规则，NaN 不等于 NaN。
=====
... 如果两个操作数都是对象，则比较它们是不是同一个对象。如果两个操作数都指向同一个对象，则相等操作符返回 true；否则，返回 false。

+
[options="header"]
|=====
|表达式 |值
|null == undefined |true
|"NaN" == NaN |false
|5 == NaN |false
|NaN == NaN |false
|NaN != NaN |true
|false == 0 |true
|true == 1 |true
|true == 2 |false
|undefined == 0 |false
|null == 0 |false
|"5" == 5 |true
|=====

. 全等（===）和不全等（!==）

.. 仅比较而不转换
+
[source, javascript, numbered]
----
var result1 = ("55" == 55);     //true
var result2 = ("55" === 55);    //false，数据类型不同
var result3 = (null === undefined)  //false
----

==== 条件操作符

----
variable = boolean_expression ? true_value : false_value;
----

==== 赋值操作符

. 复合赋值操作符
+
----
*=  /=  %=  +=  -=
<<=     >>=     >>>=
----
+
使用它们可以简化操作，但不会带来性能提升。

==== 逗号操作符

. 举例：
+
[source, javascript, numbered]
----
var num = (5, 1, 4, 8, 0);      //num 的值为0
----

=== 语句

==== if 语句

==== do-while 语句

==== while 语句

==== for 语句

==== for-in 语句

. 举例：
+
[source, javascript, numbered]
----
for (var propertyName in window) {
  document.write(propertyName);
}
----
+
.. var 操作符不是必需的，但为了保证使用局部变量，推荐上例中的做法。
.. ECMAScript 对象的属性没有顺序。因此，通过 for-in 循环输出的属性名的顺序是不可预测的。
.. 如果迭代变量值为 null 或 undefined ：
... ECMAScript 3 会抛出错误。
... ECMAScript 5 作了更正，对这种情况不再抛出错误，而只是不执行循环体。
... 为了保证最大限度的兼容性，使用 for-in 循环之前，应先检测该对象的值不是 null 或 undefined。

==== label 语句

==== break 和 continue 语句

==== with 语句

. 举例：
+
[source, javascript, numbered]
----
var qs = location.search.substring(1);
var hostName = location.hostname;
var url = location.href;

// 使用 with 进行简化
with (location) {
  var qs = search.substring(1);
  var hostName = hostname;
  var url = href;
}
----
+
[WARNING]
=====
大量使用 with 语句会导致性能下降，同时给调试代码造成困难，因此在开发大型应用程序时，不建议使用 with 语句。
=====

==== switch 语句

. 通常每个 case 最后会有一个 break 语句。如果需要混合几种情形，应在代码中添加注释，说明是有意省略了 break 关键字。
+
[source, javascript, numbered]
----
switch (i) {
  case 25:
    /* 合并两种情形 */
  case 35:
    alert('25 or 35');
    break;
  case 45:
    alert('45');
    break;
  default:
    alert('Other');
}
----

. switch 语句可以使用任何数据类型，字符串或对象都没有问题。

. 每个 case 的值不一定是常量，可以是变量，甚至是表达式。

[NOTE]
=====
switch 语句在比较值时使用的是全等操作符，因此不会发生类型转换。
=====

=== 函数

. return 语句可以不带任何返回值，函数在停止执行后将返回 undefined 值。
+
[NOTE]
=====
推荐做法是：要么让函数始终都返回一个值，要么永远都不要返回值。
=====

. 严格模式对函数有一些限制：
.. 不能把函数命名为 eval 或 arguments ；
.. 不能把参数命名为 eval 或 arguments ；
.. 不能出现两个命名参数同名的情况。

. 参数

.. ECMAScript 中，解析器不会验证参数个数以及函数签名等。

.. 在函数体内可以通过 arguments 对象来访问参数数组。（该对象与数组类似，但并不是 Array 的实例。）

.. 通过访问 arguments 对象的length 属性可以获知有多少个参数传递给了函数。
+
[source, javascript, numbered]
----
function howManyArgs() {
  alert(arguments.length);
}
howManyArgs('string', 45);  //2
howManyArgs();              //0
howManyArgs(12);            //1
----

.. arguments 的值与对应命名参数的值保持同步。
+
[source, javascript, numbered]
----
function doAdd(num1, num2) {
  arguments[1] = 10;    //num2变为10
  alert(arguments[0] + num2);
}
----
+
如果只传入了一个参数，则 num2 中就会保存 undefined 值，为 arguments[1] 设置的值不会反应到 num2 中。
严格模式下，缺少参数并重写 arguments 的值会导致语法错误。

+
[NOTE]
=====
ECMAScript 中的所有参数传递的都是值，不可能通过引用传递参数。
=====

. 没有重载

.. ECMAScirpt 没有函数签名，真正的重载不可能做到。（通过检查传入函数中参数的类型和数量并作出不同的处理，可以模仿方法的重载。）

.. 如果定义了两个名字相同的函数，则该名字只属于后定义的函数。
+
[source, javascript, numbered]
----
function addSomeNumber(num) {
  return num + 100;
}
function addSomeNumber(num) {
  return num + 200;
}
var result = addSomeNumber(100); //300
----

=== 变量、作用域和内存问题

==== 基本类型和引用类型的值

. JavaScript 不能直接操作对象的内存空间：
.. 当复制保存着对象的某个变量时，操作的是对象的引用；
.. 在为对象添加属性时，操作的是实际对象。

. 复制变量值
.. 复制基本类型的值，会在变量对象上创建一个新值，复制后不会相互影响。
.. 复制引用类型的值，复制的是一个指针，复制后改变其中一个变量，就会影响另一个变量。

. 传递参数
+
参数都是按值传递。（即使在函数内部修改了参数的值，但原始的引用仍然保持未变。）
+
[source, javascript, numbered]
----
function setName(obj) {
  obj.name = 'Nicholas';
  obj = new Object();
  obj.name = 'Greg';
}
var person = new Object();
setName(person);
alert(person.name);     //"Nicholas"
----
+
[NOTE]
=====
可以把 ECMAScript 函数的参数想象成局部变量。
=====

. 检测类型

. 检测基本类型，使用 typeof 。
+
[source, javascript, numbered]
----
var u;
var n = null;
var o = new Object();
alert(typeof u); //undefined
alert(typeof n); //object
alert(typeof o); //object
----

. 检测引用类型，使用 instanceof 。

==== 执行环境及作用域

==== 垃圾收集

== jQuery

=== 基础

==== 根据类型、类或id选择元素

[source, javascript, numbered]
----
$('*')         //选择文档中的所有元素
$('.myclass')  //选择所有已向其分配CSS类myclass的元素
$('element')   //选择所有类型为element的元素
$('#myid')     //选择id为myid的元素
----

==== 根据关系和联合选择元素

[source, javascript, numbered]
----
$('tr td')         //匹配所有作为tr元素的后代的td元素
$('tr > td')       //匹配所有作为tr元素的直接后代的td元素
$('h2 + table')    //匹配紧接在h2元素后面的table元素
$('h2 ~ table')    //匹配h2元素后面的table元素（不一定紧邻h2元素）
$('tr, td')        //匹配tr和td元素
----

==== 特性选择器

[source, javascript, numbered]
----
$('[attr]')         //选择具有attr特性的元素，不论其特性值如何
$('[attr]="val"')   //选择具有attr特性且其值为val的元素
$('[attr]!="val"')  //选择具有attr特性且其值不为val的元素
$('[attr]^="val"')  //选择具有attr特性且其值以val开头的元素
$('[attr]~="val"')  //选择具有attr特性且其值包含val的元素
$('[attr]$="val"')  //选择具有attr特性且其值以val结尾的元素
$('[attr]|="val"')  //选择具有attr特性且其值为val或以val后连接字符（val-）开头的元素
----

==== 基本过滤器

[source, javascript, numbered]
----
:eq(n)          //使用以零为基准的索引选择第n个元素
:even:odd       //选择编号为偶数或奇数的元素
:first:last     //选择第一个或最后一个元素
:gt(n):lt(n)    //选择其索引相对于其同级大于或小于n的所有元素
:header         //选择所有属于标题（h1、h2等）的元素
:not(selector)  //选择所有与选择器不匹配的元素
----

==== 内容过滤器

[source, javascript, numbered]
----
:contains('text')   //选择包含text或其子元素包含text的元素
:has('selector')    //选择至少有一个子元素与selector匹配的元素
:empty              //选择没有子元素的元素
:parent             //选择至少有一个其他元素的元素
:first-child        //选择作为其父元素的第一个子元素的元素
:last-child         //选择作为其父元素的最后一个子元素的元素
:nth-child(n)       //使用以1为起始的索引，选择作为其父元素的第n个子元素的元素
:only-child         //选择作为其父元素的唯一子元素的元素
----

==== 表单过滤器

[source, javascript, numbered]
----
:button             //选择类型为button的button元素和input元素
:checkbox           //选择复选框
:checked            //选择处于选中状态的复选框和单选按钮
:disabled:enabled   //分别选择已启用或已禁用的元素
:input              //选择input元素
:password           //选择password元素
:radio              //选择单选按钮
:reset              //选择类型为reset的input元素
:selected           //选择处于选中状态的option元素
:submit             //选择类型为submit的input元素
:text               //选择类型为text的input元素
----

==== CSS函数

[source, javascript, numbered]
----
addClass('myClass')         //将指定的类名添加到所选元素的class特性中
hasClass('myClass')         //如果已将指定类分配给所选的元素，则返回true
removeClass('myClass')      //从所选元素的class特性中删除指定的类名
toggleClass('myClass')      //如果指定的类不存在，则添加该类，否则删除该类
css('property', 'value')    //将指定的属性和值添加到所选元素的样式特性中
css('property')             //从第一个匹配的元素返回特定属性的值
----

==== DOM导航函数

[source, javascript, numbered]
----
children()          //获取所选元素的子元素
closest('selector') //遍历所选的每个元素的祖先元素，查找与指定选择器匹配的第一个元素实例
filter('selector')  //将所选元素缩减到那些与指定选择器匹配的元素
first('selector')   //遍历所选元素的后代，查找所有与指定选择器匹配的元素
next()              //获取紧接在所选元素之后的同级元素
prev()              //获取紧靠在所选元素之前的同级元素
parent()            //返回所选元素的直接父元素
sibilings()         //返回所选元素的同级元素
----

==== DOM操作函数

[source, javascript, numbered]
----
before('new') after('new')   //将new元素插入到所选元素之前或之后
insertBefore() insertAfter() //用法类似before和after，但颠倒新元素和选择器的顺序，返回新建的元素
prepend('new') append('new') //将new元素插入到所选元素中，作为第一个或最后一个子元素
prependTo() appendTo()       //用法与prepend和append相同，但颠倒新元素和选择器的顺序，返回新建的元素
empty()                      //删除所选元素的所有子元素
remove()                     //删除DOM中的所选元素
attr('name', 'val')          //将所选元素的name特性设置为val，如果特性不存在，则创建特性
removeAttr('name')           //从所选元素中删除name特性
----

==== 事件处理函数

[source, javascript, numbered]
----
click       //单击鼠标时触发
dblclick    //双击鼠标时触发
mouseenter  //鼠标进入元素所在的屏幕区域时触发
mouseleave  //鼠标离开元素所在的屏幕区域时触发
change      //元素值发生更改时触发
select      //选择元素值时触发
submit      //提交表单时触发
----

