JavaScript
==========
:icons:
:toc:
:numbered:

基础
--

<Script>元素
~~~~~~~~~~

. 属性
.. async 可选
.. charset 可选

.. defer 可选
+
立即下载、延迟执行，此属性的用途是表明脚本在执行时不会影响页面的构造。

.. language 已废弃
.. src 可选

.. type 可选
+
已不推荐使用，但考虑到约定俗成和最大限度的浏览器兼容性，可以设为 text/javascript（默认值）。

. 在使用 <script> 嵌入 JavaScript 代码时，不要在代码中的任何地方出现"</script>"字符串。
+
----
<script type="text/javascript">
    function sayScript(){
        alert("</script>");     //错误
        alert("<\/script>");    //正确
    }
</script>
----

. 如果是在 XHTML 文档中，可以省略 </script> 标签，例如：
+
----
<script type="text/javascript" src="example.js" />
----
+
但是，不能在 HTML 文档使用这种语法。原因是这种语法不符合 HTML 规范，而且也得不到某些浏览器（尤其是IE）的正确解析。
+
[NOTE]
======
- 按惯例，外部 JavaScript 文件带有 .js 扩展名，但这个扩展名不是必需的。
- 如果不使用 .js 扩展名，请确保服务器能返回正确的 MIME 类型。
======

. 带有 src 属性的 <script> 元素不应再包含额外代码。如果包含了，嵌入代码会被忽略，只有外部脚本文件会被下载并执行。

. 只要不存在 defer 和 async 属性，浏览器都会按照<script>元素在页面中出现的先后顺序对它们依次进行解析。换句话说，
在第一个 <script> 元素包含的代码解析完成后，第二个 <script> 包含的代码才会被解析，然后才是第三个、第四个……

. 按照传统做法，所有 <script> 元素都应该放在页面的 <head> 元素中。
这种做法的目的就是把所有外部文件（包括 CSS 文件和 JavaScript 文件）的引用都放在相同的地方。
对于那些需要很多 JavaScript 代码的页面来说，这会导致浏览器在呈现页面时出现明显的延迟（浏览器在遇到 <body> 标签时才开始呈现内容）。
为了避免这个问题，现代 Web 应用程序一般都把全部 JavaScript 引用放在 <body> 元素中页面内容的后面：
+
----
<!DOCTYPE html>
<html>
<head>
    <title>Example HTML Page</title>
</head>
<body>
<!-- 这里放内容 -->
<script type="text/javascript" src="example1.js"></script>
<script type="text/javascript" src="example2.js"></script>
</body>
</html>
----

. 延迟脚本
+
----
<!DOCTYPE html>
<html>
<head>
    <title>Example HTML Page</title>
    <script type="text/javascript" defer="defer" src="example1.js"></script>
    <script type="text/javascript" defer="defer" src="example2.js"></script>
</head>
<body>
<!-- 这里放内容 -->
</body>
</html>
----
.. HTML5 规范要求脚本按照它们出现的先后顺序执行，因此第一个延迟脚本会先于第二个执行，而这两个脚本会先于 DOMContentLoaded 事件执行。
.. 在现实当中，延迟脚本并不一定会按照顺序执行，也不一定会在 DOMContentLoaded 事件触发前执行，因此最好只包含一个延迟脚本。
.. defer 属性只适用于外部脚本文件。这一点在 HTML5 中已经明确规定，因此支持 HTML5 的实现会忽略给嵌入脚本设置的 defer 属性。
IE4～IE7 还支持对嵌入脚本的 defer 属性，但 IE8 及之后版本则完全支持 HTML5 规定的行为。

. 异步脚本
+
----
<!DOCTYPE html>
<html>
<head>
    <title>Example HTML Page</title>
    <script type="text/javascript" async src="example1.js"></script>
    <script type="text/javascript" async src="example2.js"></script>
</head>
<body>
<!-- 这里放内容 -->
</body>
</html>
----
.. 与defer 类似，async 只适用于外部脚本文件，并立即下载文件。但与defer不同，标记为 async 的脚本并不保证按照指定它们的先后顺序执行。
.. 确保两脚本之间互不依赖非常重要。
.. 指定 async 属性的目的是不让页面等待脚本下载和执行，从而异步加载页面其他内容。为此，建议异步脚本不要在加载期间修改DOM。
.. 异步脚本一定会在页面的 load 事件前执行，但可能会在DOMContentLoaded 事件触发之前或之后执行。

. 文档模式
.. 混杂模式（quirks mode）

.. 标准模式（standards mode）
+
----
<!-- HTML 4.01 严格型 -->
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN"
        "http://www.w3.org/TR/html4/strict.dtd">

<!-- XHTML 1.0 严格型 -->
<!DOCTYPE html PUBLIC
        "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">

<!-- HTML 5 -->
<!DOCTYPE html>
----

.. 准标准模式（almost standards mode）
+
准标准模式与标准模式非常接近，它们的差异几乎可以忽略不计。
+
----
<!-- HTML 4.01 过渡型 -->
<!DOCTYPE HTML PUBLIC
        "-//W3C//DTD HTML 4.01 Transitional//EN"
        "http://www.w3.org/TR/html4/loose.dtd">

<!-- HTML 4.01 框架集型 -->
<!DOCTYPE HTML PUBLIC
        "-//W3C//DTD HTML 4.01 Frameset//EN"
        "http://www.w3.org/TR/html4/frameset.dtd">

<!-- XHTML 1.0 过渡型 -->
<!DOCTYPE html PUBLIC
        "-//W3C//DTD XHTML 1.0 Transitional//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<!-- XHTML 1.0 框架集型 -->
<!DOCTYPE html PUBLIC
        "-//W3C//DTD XHTML 1.0 Frameset//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-frameset.dtd">
----

<NoScript>元素
~~~~~~~~~~~~

----
<html>
<head>
    <title>Example HTML Page</title>
    <script type="text/javascript" defer="defer" src="example1.js"></script>
    <script type="text/javascript" defer="defer" src="example2.js"></script>
</head>
<body>
<noscript>
    <p>本页面需要浏览器支持（启用）JavaScript。
</noscript>
</body>
</html>
----

jQuery
------

----
//根据类型、类或id选择元素
$('*')         //选择文档中的所有元素
$('.myclass')  //选择所有已向其分配CSS类myclass的元素
$('element')   //选择所有类型为element的元素
$('#myid')     //选择id为myid的元素

// 根据关系和联合选择元素
$('tr td')         //匹配所有作为tr元素的后代的td元素
$('tr > td')       //匹配所有作为tr元素的直接后代的td元素
$('h2 + table')    //匹配紧接在h2元素后面的table元素
$('h2 ~ table')   //匹配h2元素后面的table元素（不一定紧邻h2元素）
$('tr, td')        //匹配tr和td元素

//特性选择器
$('[attr]')        //选择具有attr特性的元素，不论其特性值如何
$('[attr]="val"')  //选择具有attr特性且其值为val的元素
$('[attr]!="val"') //选择具有attr特性且其值不为val的元素
$('[attr]^="val"') //选择具有attr特性且其值以val开头的元素
$('[attr]~="val"')    //选择具有attr特性且其值包含val的元素
$('[attr]$="val"')   //选择具有attr特性且其值以val结尾的元素
$('[attr]|="val"') //选择具有attr特性且其值为val或以val后连接字符（val-）开头的元素

//基本过滤器
:eq(n)          //使用以零为基准的索引选择第n个元素
:even:odd       //选择编号为偶数或奇数的元素
:first:last     //选择第一个或最后一个元素
:gt(n):lt(n)    //选择其索引相对于其同级大于或小于n的所有元素
:header         //选择所有属于标题（h1、h2等）的元素
:not(selector)  //选择所有与选择器不匹配的元素

//内容过滤器
:contains('text')   //选择包含text或其子元素包含text的元素
:has('selector')    //选择至少有一个子元素与selector匹配的元素
:empty              //选择没有子元素的元素
:parent             //选择至少有一个其他元素的元素
:first-child        //选择作为其父元素的第一个子元素的元素
:last-child         //选择作为其父元素的最后一个子元素的元素
:nth-child(n)       //使用以1为起始的索引，选择作为其父元素的第n个子元素的元素
:only-child         //选择作为其父元素的唯一子元素的元素

//表单过滤器
:button             //选择类型为button的button元素和input元素
:checkbox           //选择复选框
:checked            //选择处于选中状态的复选框和单选按钮
:disabled:enabled   //分别选择已启用或已禁用的元素
:input              //选择input元素
:password           //选择password元素
:radio              //选择单选按钮
:reset              //选择类型为reset的input元素
:selected           //选择处于选中状态的option元素
:submit             //选择类型为submit的input元素
:text               //选择类型为text的input元素

//CSS函数
addClass('myClass')     //将指定的类名添加到所选元素的class特性中
hasClass('myClass')     //如果已将指定类分配给所选的元素，则返回true
removeClass('myClass')  //从所选元素的class特性中删除指定的类名
toggleClass('myClass')  //如果指定的类不存在，则添加该类，否则删除该类
css('property', 'value')    //将指定的属性和值添加到所选元素的样式特性中
css('property')         //从第一个匹配的元素返回特定属性的值

//DOM导航函数
children()          //获取所选元素的子元素
closest('selector') //遍历所选的每个元素的祖先元素，查找与指定选择器匹配的第一个元素实例
filter('selector')  //将所选元素缩减到那些与指定选择器匹配的元素
first('selector')   //遍历所选元素的后代，查找所有与指定选择器匹配的元素
next()              //获取紧接在所选元素之后的同级元素
prev()              //获取紧靠在所选元素之前的同级元素
parent()            //返回所选元素的直接父元素
sibilings()         //返回所选元素的同级元素

//DOM操作函数
before('new')after('new')   //将new元素插入到所选元素之前或之后
insertBefore()insertAfter() //用法与before和after相同，但会颠倒新元素和选择器的顺序，这些函数返回新建的元素
prepend('new')append('new') //将new元素插入到所选元素中，作为第一个或最后一个子元素
prependTo()appendTo()       //用法与prepend和append相同，但会颠倒新元素和选择器的顺序，这些函数返回新建的元素
empty()                     //删除所选元素的所有子元素
remove()                    //删除DOM中的所选元素
attr('name', 'val')         //将所选元素的name特性设置为val，如果特性不存在，则创建特性
removeAttr('name')          //从所选元素中删除name特性

//事件处理函数
click       //单击鼠标时触发
dblclick    //双击鼠标时触发
mouseenter  //鼠标进入元素所在的屏幕区域时触发
mouseleave  //鼠标离开元素所在的屏幕区域时触发
change      //元素值发生更改时触发
select      //选择元素值时触发
submit      //提交表单时触发
----
