= Linux
:icons:
:toc:
:numbered:

== 常用命令

=== 目录类

. mkdir
+
创建目录

. cd
+
进入目录

. rmdir
+
删除目录

. rm
+
删除文件或目录。
+
----
rm -rf
----
+
强制删除目录下所有的东西，-r 表示递归，-f 表示强制。

=== 文件类

. touch
+
创建文件或修改文件时间

. cp
+
拷贝文件
+
----
cp myFile myFile.bk
----

. mv
+
移动文件
+
----
mv myFile myDir
----

=== 其他

. CentOS 7 初始化搭建
+
http://www.vultr.com/docs/initial-setup-of-a-centos-7-server[参考]

. 时区和 NTP 设置
+
http://www.vultr.com/docs/setup-timezone-and-ntp-on-centos-6[参考]

.. 修改时区
+
----
date    # 查看当前时间

rm -rf /etc/localtime   # 删除当前时区
ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime  # 设置时区为上海

vi /etc/sysconfig/clock # 使用 vi 修改配置

ZONE="Asia/Shanghai"
UTC=false
ARC=false

:wq #保存退出

hwclock --systohc --localtime   # 将系统时间写入硬件时钟

hwclock # 查看结果
----

.. 设置 NTP
+
----
ntpd --version  # 查看 NTP 版本，默认为 4.2.6p5

service ntpd stop   # 停止服务

... （待续）

----

. 显示用法手册
+
----
# 如果还未安装手册，可用如下命令
yum install man-pages
----

== 基础知识

=== 系统启动和关闭

. 系统启动过程
.. BIOS开机自检 →
.. 操作系统接管硬件 →
.. 读入 /boot 目录下的内核文件 →
.. 运行 Init，此进程首先要读取配置文件 /etc/inittab →

.. 根据运行级别（runlevel）确定需要运行哪些程序 →
... Linux系统有7个运行级别(runlevel)：
+
----
运行级别0：系统停机状态，系统默认运行级别不能设为0，否则不能正常启动
运行级别1：单用户工作状态，root权限，用于系统维护，禁止远程登陆
运行级别2：多用户状态(没有NFS)
运行级别3：完全的多用户状态(有NFS)，登陆后进入控制台命令运行级别4：系统未使用，保留
运行级别5：X11控制台，登陆后进入图形GUI模式
运行级别6：系统正常关闭并重启，默认运行级别不能设为6，否则不能正常启动
----

.. 系统初始化（/etc/rc.d/init.d/） →

.. 建立终端，用户登录系统 →

... 用户登录方式一般有三种：
.... 命令行登录
.... ssh登录
.... 图形界面登录

.. Login Shell

... 图形模式与文字模式的切换方式
.... Linux预设提供了六个命令窗口终端机。
.... 默认登录的是第一个窗口，也就是tty1，这个六个窗口分别为tty1,tty2 … tty6，可以按下Ctrl + Alt + F1 ~ F6 来切换。
.... 如果安装了图形界面，默认情况是进入图形界面，此时你就可以按Ctrl + Alt + F1 ~ F6来进入其中一个命令窗口界面。
.... 当你进入命令窗口界面后再返回图形界面只要按下Ctrl + Alt + F7 。
.... 如果用的是 vmware 虚拟机，命令窗口切换的快捷键为 Alt + Space + F1~F6. 如果在图形界面下请按Alt + Shift + Ctrl + F1~F6 切换。

. 系统关机
+
正确的关机流程为：sync > shutdown > reboot > halt
+
----
sync 将数据由内存同步到硬盘中。

shutdown –h 10 ‘This server will shutdown after 10 mins’ 这个命令会显示消息在登陆用户的当前屏幕中。

Shutdown –h now 立刻关机

Shutdown –h 20:25 系统会在今天20:25关机

Shutdown –h +10 十分钟后关机

Shutdown –r now 系统立刻重启

Shutdown –r +10 系统十分钟后重启

reboot 重启，等同于 shutdown –r now

halt 关闭系统，等同于shutdown –h now 和 poweroff
----

=== 系统分区和格式化

. 分区类型

.. 主分区
+
最多只能有4个。

.. 扩展分区
... 最多只能有1个。
... 主分区+扩展分区，最多有4个。
... 不能写入数据，只能包含逻辑分区。

.. 逻辑分区
+
逻辑分区号从5开始（即使扩展分区3和4没有使用）

. 格式化

. 分区（硬件）设备文件名
+
[options="autowidth"]
|===
|硬件 |设备文件名
|IDE硬盘 |/dev/hd[a-d]
|SCSI/SATA/USB硬盘 |/dev/sd[a-p]
|光驱 |/dev/cdrom 或 /dev/hdc
|软盘 |/dev/fd[0-1]
|打印机（25针） |/dev/lp[0-2]
|打印机（USB） |/dev/usb/lp[0-15]
|鼠标 |/dev/mouse
|===
+
举例：
+
----
/dev/hda1   （表示IDE硬盘a的第1个分区）
----

. 挂载
+
挂载点（目录，类似于Windows中的盘符）

.. 必须分区
... / （根分区）
... swap分区 （交换分区）
.... 内存在4G以内，则分配2倍内存大小
.... 内存超过4G，则分配内存同等大小
.... 做实验不超过2GB即可

.. 推荐分区
... /boot （启动分区，200MB）

=== 系统目录结构

. 登录系统后，输入 ls 命令可以查看目录结构：

.. /bin
+
bin是Binary的缩写, 这个目录存放着最经常使用的命令。

.. /boot
+
这里存放的是启动Linux时使用的一些核心文件，包括一些连接文件以及镜像文件。

.. /dev
+
dev是Device(设备)的缩写, 该目录下存放的是Linux的外部设备，在Linux中访问设备的方式和访问文件的方式是相同的。

.. /etc
+
这个目录用来存放所有的系统管理所需要的配置文件和子目录。

.. /home
+
用户的主目录，在Linux中，每个用户都有一个自己的目录，一般该目录名是以用户的账号命名的。

.. /lib
+
这个目录里存放着系统最基本的动态连接共享库，其作用类似于Windows里的DLL文件。几乎所有的应用程序都需要用到这些共享库。

.. /lost+found
+
这个目录一般情况下是空的，当系统非法关机后，这里就存放了一些文件。

.. /media
+
linux系统会自动识别一些设备，例如U盘、光驱等等，当识别后，linux会把识别的设备挂载到这个目录下。

.. /mnt
+
系统提供该目录是为了让用户临时挂载别的文件系统的，我们可以将光驱挂载在/mnt/上，然后进入该目录就可以查看光驱里的内容了。

.. /opt
+
这是给主机额外安装软件所摆放的目录。比如你安装一个ORACLE数据库则就可以放到这个目录下。默认是空的。

.. /proc
+
这个目录是一个虚拟的目录，它是系统内存的映射，我们可以通过直接访问这个目录来获取系统信息。
这个目录的内容不在硬盘上而是在内存里，我们也可以直接修改里面的某些文件，比如可以通过下面的命令来屏蔽主机的ping命令，使别人无法ping你的机器：
+
----
echo 1 > /proc/sys/net/ipv4/icmp_echo_ignore_all
----

.. /root
+
该目录为系统管理员，也称作超级权限者的用户主目录。

.. /sbin
+
s就是Super User的意思，这里存放的是系统管理员使用的系统管理程序。

.. /selinux
+
这个目录是Redhat/CentOS所特有的目录，Selinux是一个安全机制，类似于windows的防火墙，但是这套机制比较复杂，这个目录就是存放selinux相关的文件的。

.. /srv
+
该目录存放一些服务启动之后需要提取的数据。

.. /sys

... 这是linux2.6内核的一个很大的变化。该目录下安装了2.6内核中新出现的一个文件系统 sysfs 。
... sysfs文件系统集成了下面3种文件系统的信息：针对进程信息的proc文件系统、针对设备的devfs文件系统以及针对伪终端的devpts文件系统。
... 该文件系统是内核设备树的一个直观反映。
... 当一个内核对象被创建的时候，对应的文件和目录也在内核对象子系统中被创建。

.. /tmp
+
这个目录是用来存放一些临时文件的。

.. /usr
+
这是一个非常重要的目录，用户的很多应用程序和文件都放在这个目录下，类似于windows下的program files目录。

.. /usr/bin
+
系统用户使用的应用程序。

.. /usr/sbin
+
超级用户使用的比较高级的管理程序和系统守护程序。

.. /usr/src
+
内核源代码默认的放置目录。

.. /var
+
这个目录中存放着在不断扩充着的东西，我们习惯将那些经常被修改的目录放在这个目录下。包括各种日志文件。

