= Linux
:icons:
:toc:
:numbered:
:toclevels: 4
:source-highlighter: highlightjs
:highlightjsdir: highlight
:highlightjs-theme: monokai

:source-language: bash

== 命令

命令格式

----
命令 选项 参数
----
- 个别命令不遵循此格式
- 有多个选项时，可以写在一起
- 简化选项和完整选项
    * -a 等于 --all

=== bzip2

[source]
----
# 压缩为.bz2格式，不保留源文件
bzip2 源文件

# 压缩之后保留源文件
bzip2 -k 源文件

# 解压缩，-k保留压缩文件（2种方法）
bzip2 -d 压缩文件
bunzip2 压缩文件
----

[NOTE]
====
bzip2 命令不能压缩目录
====

=== cd

变更目录

[source]
----
cd 目录

cd ~    # 进入当前用户的home目录
cd -    # 进入上次目录
cd ..   # 进入上一级目录
cd .    # 进入当前目录
----

=== cp

复制文件或目录

[source]
----
cp 选项 原文件或目录 目标目录
----

. -a   相当于 -dpr
. -d   若源文件是链接文件，则复制链接属性
. -p   连带文件属性复制
. -r   复制目录

=== find

搜索文件

[source]
----
find 搜索范围 搜索条件
----

. 避免大范围搜索，会非常耗费系统资源
. find 是在系统当中搜索符合条件的文件名。如果需要匹配，使用通配符匹配，通配符是完全匹配。

. 示例
+
[source, bash, numbered]
----
# 使用通配符
#   *  匹配任意内容
#   ?  匹配任意一个字符
#   [] 匹配任意一个中括号内的字符
find /root -name "install.log*"

# 不区分大小写
find /root -iname install.log

# 按照所有者搜索
find /root -user root

# 查找没有所有者的文件
# 一般情况下，没有所有者的文件即为垃圾文件，但有两个例外：
# （1）Linux内核直接产生，例如内存交换目录中的文件；
# （2）外部产生的文件，例如Windows系统中创建的文件，通过U盘拷贝到Linux系统中。
find /root -nouser

# 查找10天前修改的文件
find /var/log/ -mtime +10

    #   atime   文件访问时间
    #   ctime   改变文件属性
    #   mtime   修改文件内容

    #   -10 10天内修改的文件
    #    10 10天当天修改的文件
    #   +10 10天前修改的文件

# 查找文件大小是25KB的文件
find . -size 25k

    #   -25k    小于25KB的文件
    #    25k    等于25KB的文件
    #   +25k    大于25KB的文件
    #   注意：输入单位时，k 必须小写，M 必须大写。

# 查找 i 节点是262422的文件
find . -inum 262422

# 查找/etc/目录下，大于20KB且小于50KB的文件
find /etc -size +20k -a -size -50k
    #   -a  and 逻辑与
    #   -o  or  逻辑或

# 查找/etc/目录下，大于20KB且小于50KB的文件，并显示详细信息
# -exec/-ok 命令 {} \;  对搜索结果执行操作
find /etc -size +20k -a -size -50k -exec ls -lh {} \;
----

=== grep

在文件当中匹配符合条件的字符串，使用正则表达式进行匹配，匹配方式为包含匹配。

[source]
----
grep 选项 字符串 文件名
----

. -i   忽略大小写
. -v   排除指定字符串

=== gzip

.gz格式压缩

[source]
----
# 压缩为.gz格式的压缩文件，源文件会消失
gzip 源文件

# 压缩为.gz格式，源文件保留
gzip -c 源文件 > 压缩文件

# 压缩目录下所有的子文件，但是不能压缩目录
gzip -r 目录

# 解压缩文件（2种方法）
gzip -d 压缩文件
gunzip 压缩文件
----

=== info

详细命令帮助

[source]
----
info 命令
----

. -回车：进入子帮助页面（带有*号标记）
. -u  ：进入上层页面
. -n  ：进入下一个帮助小节
. -p  ：进入上一个帮助小节
. -q  ：退出

=== last

查询当前登录和过去登录的用户信息。

. last命令默认读取/var/log/wtmp文件数据。

. 命令输出：
.. 用户名
.. 登录终端
.. 登录IP
.. 登录时间
.. 退出时间（在线时间）

=== lastlog

查看所有用户的最后一次登录时间。

. lastlog命令默认读取/var/log/lastlog文件内容

. 命令输出
.. 用户名
.. 登录终端
.. 登录IP
.. 最后一次登录时间

=== ll

相当于 ls -l

=== ln

生成链接文件

[source]
----
ln -s 原文件 目标文件
----

. -s   创建软链接

=== locate

在后台数据库中按文件名搜索（比find速度快）

[source]
----
locate 文件名
----

. locate命令所搜索的后台数据库：/var/lib/mlocate （不同的Linux发行版，数据库名称可能有差别）。
. 该数据库并非实时更新，刚创建的文件可能搜不到，此时可用命令 updatedb 先更新数据库再搜索。

. locate的搜索行为由配置文件 /etc/updatedb.conf 定义：
+
[source]
----
# 开启搜索限制
PRUNE_BIND_MOUNTS = "yes"

# 搜索时，不搜索的文件系统
PRUNEFS =

# 搜索时，不搜索的文件类型
PRUNENAMES =

# 搜索时，不搜索的路径
PRUNEPATHS =
----

=== logout

退出登录

=== ls

列出文件或目录

[source]
----
ls 选项 文件或目录
----

. -a  显示所有文件，包含隐藏文件
. -d  查看目录属性
. -h  人性化显示文件大小
. -i  显示inode

. -l  显示详细信息
+
[source, shell]
----
[root@localhost ~]# ls
anaconda-ks.cfg
[root@localhost ~]# ls -l
总用量 4
-rw-------. 1 root root 1326 5月   9 07:27 anaconda-ks.cfg
----
+
[NOTE]
====
. 一共10位
. 第1位的“-”：表示文件类型（-文件，d目录，l软链接文件）
. 后9位分3组，每3位为1组，分别代表：u所有者，g所属组，o其他人 （权限表示为：r读，w写，x执行）
====

=== man

查看帮助

[source]
----
man 命令
----

. man的级别
+
[source]
----
#1   查看命令的帮助
#2   查看可被内核调用的函数的帮助
#3   查看函数和函数库的帮助
#4   查看特殊文件的帮助（主要是/dev目录下的文件）
#5   查看配置文件的帮助
#6   查看游戏的帮助
#7   查看其它杂项的帮助
#8   查看系统管理员可用命令的帮助
#9   查看和内核相关文件的帮助
----

. 查看命令拥有那个级别的帮助
+
[source]
----
man -f 命令
# 相当于
whatis 命令

man -5 passwd
man -8 ifconfig
----

. 查看和命令相关的所有帮助
+
[source]
----
man -k 命令
# 相当于
apropos 命令
----

. 选项帮助
+
[source]
----
命令 --help

ls --help
----

. shell内部命令帮助
+
[source]
----
help shell内部命令

whereis cd  # 确定是否是shell内部命令。如果只能找到帮助、找不到可执行文件，说明是内部命令。
help cd     # 获取内部命令帮助
----

=== mkdir

创建目录

[source]
----
mkdir 单级目录
mkdir -p 多级目录
----

=== mount

挂载

[source]
----
# 格式
mount [-t 文件系统] [-o 特殊选项] 设备文件名 挂载点

# 查询系统中已经挂载的设备
mount

# 依据配置文件/etc/fstab的内容，自动挂载
mount -a
----

. -t 文件系统：加入文件系统类型来指定挂载的类型，ext3、ext4、iso9660等

. -o 特殊选项：可以指定挂载的额外选项

.. atime/noatime
+
访问分区文件时，是否更新文件的访问时间，默认为更新。

.. async/sync
+
默认为异步。

.. auto/noauto
+
mount -a 命令执行时，是否自动安装/etc/fstab文件内容挂载，默认为自动。

.. defaults
+
定义默认值，相当于rw、suid、dev、exec、auto、nouser、async这七个选项。

.. exec/noexec
+
设定是否允许在文件系统中执行可执行文件，默认是exec允许。

.. remount
+
重新挂载已挂载的文件系统，一般用于指定修改特殊权限。

.. rw/ro
+
文件系统挂载时，是否具有读写权限，默认是rw。

.. suid/nosuid
+
设定文件系统是否具有SUID和SGID的权限，默认是具有。

.. user/nouser
+
设定文件系统是否允许普通用户挂载，默认是不允许，只有root可以挂载分区。

.. usrquota
+
写入代表文件系统支持用户磁盘配额，默认不支持。

.. grpquota
+
写入代表文件系统支持组磁盘配额，默认不支持。

. 挂载光盘
+
[source]
----
# 建立挂载点
mkdir /mnt/cdrom/

# 挂载光盘（2种方法）
mount /dev/sr0 /mnt/cdrom/
mount -t iso9660 /dev/cdrom /mnt/cdrom/

# (卸载)。如果当前工作目录就是光盘目录，需要先退出光盘目录，才能正常卸载。
umount /mnt/cdrom/
----

. 挂载U盘
+
[source]
----
# 查看U盘设备文件名
fdisk -l

# 假设只有一块硬盘sda，则挂载U盘为sdb。vfat即fat32格式。
mount -t vfat /dev/sdb1 /mnt/usb/
----
+
[NOTE]
====
Linux默认不支持NTFS文件系统，解决办法（只读、不能写入）：

- 重新编译内核
- 下载NTFS-3G
====

=== mv

剪切或改名

[source]
----
mv 原文件或目录 目标目录
----

=== ping

. 指定次数为4次，数据包大小为 32767 Bytes：
+
[source]
----
ping -c 4 -s 32767 ip
----

. Windows下，指定次数为6次，ping包大小为 1500 Bytes：
+
[source]
----
ping -n 6 -l 1500 ip
----

=== pwd

（打印）查询工作目录

=== rm

删除文件或目录

. -r 表示递归（即包含子目录）
. -f 表示强制
+
[source]
----
rm -rf  # 强制删除目录下所有的东西
----

=== rmdir

删除空目录

=== runlevel

查询系统运行级别

=== shutdown

[source]
----
shutdown 选项 时间
----

. -c ：取消前一个关机命令
. -h ：关机
. -r ：重启

[TIP]
====
. 其他关机命令：
.. halt
.. poweroff
.. init 0

. 其他重启命令：
.. reboot
.. init 6

. init参数的含义（即系统运行级别）：
.. 0 关机
.. 1 单用户
.. 2 不完全多用户，不含NFS服务
.. 3 完全多用户
.. 4 未分配
.. 5 图形界面
.. 6 重启
====

=== tar

[source]
----
# 打包
tar -cvf 打包文件名 源文件

# 解包
tar -xvf 打包文件名

# 打包且压缩
tar -zcvf 压缩包名.tar.gz 源文件
tar -jcvf 压缩包名.tar.bz2 源文件

# 解压缩且解包
tar -zxvf 压缩包名.tar.gz
tar -jxvf 压缩包名.tar.bz2

# 测试
tar -ztvf 压缩包名.tar.gz
----

. -c ：打包
. -v ：显示过程
. -f ：指定打包后的文件名
. -x ：解包
. -z ：压缩为.tar.gz格式
. -j ：压缩为.tar.bz2格式
. -t ：测试（查看压缩包中的内容，不实际解压）

=== touch

创建文件或修改文件时间

=== unzip

解压缩文件

[source]
----
unzip 压缩文件
----

=== w

查看登录用户信息。

命令输出：

. user: 登录的用户名
. tty: 登录终端
. from: 从哪个IP登录
. login@: 登录时间
. idle: 用户闲置时间
. jcpu: 指的是和该终端连接的所有进程占用的时间。这个时间里不包括过去的后台作业时间，但包括当前正在运行的后台作业所占用的时间。
. pcpu: 指当前进程所占用的时间
. what: 当前正在运行的命令

=== whereis

搜索命令所在路径及帮助文档所在位置

[source]
----
whereis 命令名
----

. -b   只查找可执行文件
. -m   只查找帮助文件

=== which

搜索命令所在路径及别名

=== who

查看登录用户信息。

命令输出：

. 用户名
. 登录终端
. 登录时间（登录来源IP）

=== zip

. 压缩文件
+
[source]
----
zip 压缩文件名 源文件
----

. 压缩目录
+
[source]
----
zip -r 压缩文件名 源目录
----

=== $PATH

环境变量，定义的是系统搜索命令的路径。

[source]
----
echo $PATH
----


== 基础知识

=== 系统启动和关闭

. 系统启动过程
.. BIOS开机自检 →
.. 操作系统接管硬件 →
.. 读入 /boot 目录下的内核文件 →
.. 运行 Init，此进程首先要读取配置文件 /etc/inittab →

.. 根据运行级别（runlevel）确定需要运行哪些程序 →
... Linux系统有7个运行级别(runlevel)：
+
----
运行级别0：系统停机状态，系统默认运行级别不能设为0，否则不能正常启动
运行级别1：单用户工作状态，root权限，用于系统维护，禁止远程登陆
运行级别2：多用户状态(没有NFS)
运行级别3：完全的多用户状态(有NFS)，登陆后进入控制台命令运行级别4：系统未使用，保留
运行级别5：X11控制台，登陆后进入图形GUI模式
运行级别6：系统正常关闭并重启，默认运行级别不能设为6，否则不能正常启动
----

.. 系统初始化（/etc/rc.d/init.d/） →

.. 建立终端，用户登录系统 →

... 用户登录方式一般有三种：
.... 命令行登录
.... ssh登录
.... 图形界面登录

.. Login Shell

... 图形模式与文字模式的切换方式
.... Linux预设提供了六个命令窗口终端机。
.... 默认登录的是第一个窗口，也就是tty1，这个六个窗口分别为tty1,tty2 … tty6，可以按下Ctrl + Alt + F1 ~ F6 来切换。
.... 如果安装了图形界面，默认情况是进入图形界面，此时你就可以按Ctrl + Alt + F1 ~ F6来进入其中一个命令窗口界面。
.... 当你进入命令窗口界面后再返回图形界面只要按下Ctrl + Alt + F7 。
.... 如果用的是 vmware 虚拟机，命令窗口切换的快捷键为 Alt + Space + F1~F6. 如果在图形界面下请按Alt + Shift + Ctrl + F1~F6 切换。

. 系统关机
+
正确的关机流程为：sync > shutdown > reboot > halt
+
[source]
----
sync 将数据由内存同步到硬盘中。

shutdown –h 10 ‘This server will shutdown after 10 mins’ 这个命令会显示消息在登陆用户的当前屏幕中。

Shutdown –h now 立刻关机

Shutdown –h 20:25 系统会在今天20:25关机

Shutdown –h +10 十分钟后关机

Shutdown –r now 系统立刻重启

Shutdown –r +10 系统十分钟后重启

reboot 重启，等同于 shutdown –r now

halt 关闭系统，等同于shutdown –h now 和 poweroff
----

=== 系统分区和格式化

. 分区类型

.. 主分区
+
最多只能有4个。

.. 扩展分区
... 最多只能有1个。
... 主分区+扩展分区，最多有4个。
... 不能写入数据，只能包含逻辑分区。

.. 逻辑分区
+
逻辑分区号从5开始（即使扩展分区3和4没有使用）

. 格式化

. 分区（硬件）设备文件名
+
[options="autowidth"]
|===
|硬件 |设备文件名
|IDE硬盘 |/dev/hd[a-d]
|SCSI/SATA/USB硬盘 |/dev/sd[a-p]
|光驱 |/dev/cdrom 或 /dev/hdc
|软盘 |/dev/fd[0-1]
|打印机（25针） |/dev/lp[0-2]
|打印机（USB） |/dev/usb/lp[0-15]
|鼠标 |/dev/mouse
|===
+
举例：
+
[source]
----
/dev/hda1   （表示IDE硬盘a的第1个分区）
----

. 挂载
+
挂载点（目录，类似于Windows中的盘符）

.. 必须分区
... / （根分区）
... swap分区 （交换分区）
.... 内存在4G以内，则分配2倍内存大小
.... 内存超过4G，则分配内存同等大小
.... 做实验不超过2GB即可

.. 推荐分区
... /boot （启动分区，200MB）

=== 系统目录结构

登录系统后，输入 ls 命令可以查看目录结构：

[options="autowidth"]
|===
|目录 |备注
|/bin   |bin是Binary的缩写, 这个目录存放着最经常使用的命令。
|/boot  |这里存放的是启动Linux时使用的一些核心文件，包括一些连接文件以及镜像文件。
|/dev   |dev是Device(设备)的缩写, 该目录下存放的是Linux的外部设备，在Linux中访问设备的方式和访问文件的方式是相同的。
|/etc   |这个目录用来存放所有的系统管理所需要的配置文件和子目录。
|/home  |用户的主目录，在Linux中，每个用户都有一个自己的目录，一般该目录名是以用户的账号命名的。
|/lib   |这个目录里存放着系统最基本的动态连接共享库，其作用类似于Windows里的DLL文件。几乎所有的应用程序都需要用到这些共享库。
|/lost+found    |这个目录一般情况下是空的，当系统非法关机后，这里就存放了一些文件。
|/media |linux系统会自动识别一些设备，例如U盘、光驱等等，当识别后，linux会把识别的设备挂载到这个目录下。
|/mnt   |系统提供该目录是为了让用户临时挂载别的文件系统的，我们可以将光驱挂载在/mnt/上，然后进入该目录就可以查看光驱里的内容了。
|/opt   |这是给主机额外安装软件所摆放的目录。比如你安装一个ORACLE数据库则就可以放到这个目录下。默认是空的。
|/proc  |
    这个目录是一个虚拟的目录，它是系统内存的映射，我们可以通过直接访问这个目录来获取系统信息。

    这个目录的内容不在硬盘上而是在内存里，我们也可以直接修改里面的某些文件，比如可以通过下面的命令来屏蔽主机的ping命令，
    使别人无法ping你的机器： echo 1 > /proc/sys/net/ipv4/icmp_echo_ignore_all
|/root  |该目录为系统管理员，也称作超级权限者的用户主目录。
|/sbin  |s就是Super User的意思，这里存放的是系统管理员使用的系统管理程序。
|/selinux   |
    这个目录是Redhat/CentOS所特有的目录，Selinux是一个安全机制，类似于windows的防火墙，但是这套机制比较复杂，
    这个目录就是存放selinux相关的文件的。
|/srv   |该目录存放一些服务启动之后需要提取的数据。
|/sys   |
    这是linux2.6内核的一个很大的变化。该目录下安装了2.6内核中新出现的一个文件系统 sysfs 。

    sysfs文件系统集成了下面3种文件系统的信息：针对进程信息的proc文件系统、针对设备的devfs文件系统以及针对伪终端的devpts文件系统。

    该文件系统是内核设备树的一个直观反映。

    当一个内核对象被创建的时候，对应的文件和目录也在内核对象子系统中被创建。
|/tmp   |这个目录是用来存放一些临时文件的。
|/usr   |这是一个非常重要的目录，用户的很多应用程序和文件都放在这个目录下，类似于windows下的program files目录。
|/usr/bin   |系统用户使用的应用程序。
|/usr/sbin  |超级用户使用的比较高级的管理程序和系统守护程序。
|/usr/src   |内核源代码默认的放置目录。
|/var   |这个目录中存放着在不断扩充着的东西，我们习惯将那些经常被修改的目录放在这个目录下。包括各种日志文件。
|===

=== 其他

. CentOS 7 初始化搭建
+
http://www.vultr.com/docs/initial-setup-of-a-centos-7-server[参考]

. 时区和 NTP 设置
+
http://www.vultr.com/docs/setup-timezone-and-ntp-on-centos-6[参考]

.. 修改时区
+
[source]
----
date    # 查看当前时间

rm -rf /etc/localtime   # 删除当前时区
ln -s /usr/share/zoneinfo/Asia/Shanghai /etc/localtime  # 设置时区为上海

vi /etc/sysconfig/clock # 使用 vi 修改配置

ZONE="Asia/Shanghai"
UTC=false
ARC=false

:wq #保存退出

hwclock --systohc --localtime   # 将系统时间写入硬件时钟

hwclock # 查看结果
----

.. 设置 NTP
+
[source]
----
ntpd --version  # 查看 NTP 版本，默认为 4.2.6p5

service ntpd stop   # 停止服务

... （待续）

----

. 显示用法手册
+
[source]
----
# 如果还未安装手册，可用如下命令
yum install man-pages
----

== 常见问题

=== 虚拟机环境安装完成后，如何自动启动网络并获取IP？

. Red Hat
.. 使用命令 setup 打开配置工具，选择网络配置，设定IP、子网掩码、DNS服务器等信息。
.. 使用如下命令重启网络服务：
+
[source]
----
service network restart
----

. CentOS_6
.. 虚拟机网络适配器使用桥接模式（自动）
.. 使用命令 ifconfig 查看网络配置，如果有 eth0 ，试试用如下命令打开网卡：
+
[source]
----
ifup eth0
----

.. 或者使用如下命令手工编辑配置文件，将 ONBOOT=no 改为 ONBOOT=yes 。
+
[source]
----
vi /etc/sysconfig/network-scripts/ifcfg-eth0

:q      # 不保存退出vi
:wq     # 保存退出
----

.. 重启网络服务

. CentOS_7
.. 虚拟机网络适配器使用NAT模式
.. eth0 对应变成了 ens33，使用如下命令编辑配置文件，将 ONBOOT=no 改为 ONBOOT=yes 。
+
[source]
----
vi /etc/sysconfig/network-scripts/ifcfg-ens33
----

.. 重启网络服务

=== 命令行窗口的命令提示符有什么含义？

[source,shell]
----
[root@localhost ~]#
----
. root：当前登录用户
. localhost：主机名
. ~：当前所在目录（家目录）
. #：超级用户的提示符（普通用户的提示符是 $）


=== 如何修改 SSH 默认端口（22）？    [[x_ChangeDefaultSSHPort]]
（以 CentOS_7 为例）

. SSH 远程登录
+
[source]
----
# 默认端口
ssh name@remoteserver

# 非默认端口
ssh name@remoteserver -p Your_Port_Number
----

. 修改ssh配置文件，增加新的端口：
+
[source]
----
# CentOS
vi /etc/ssh/sshd_config

# Ubuntu
sudo vim /etc/ssh/sshd_config
----
+
按【I】或【Insert】进入编辑模式，在默认端口后增加一行：
+
[source]
----
Port 22
Port Your_New_SSH_Port
----
+
按【Esc】，输入“:wq”保存退出。

. 重启 SSH 服务
+
[source]
----
# CentOS
service sshd restart

# Ubuntu
sudo service ssh restart
----

[[x_firewall]]
. 如果启用了防火墙，需要添加新开的端口：
+
[source,bash,numbered]
----
# CentOS_7 默认使用 firewalld ，查看是否运行
firewall-cmd --state

# 查看端口
firewall-cmd --permanent --list-port

# 添加端口
firewall-cmd --permanent --zone=public --add-port=Your_New_SSH_Port/tcp

# 删除端口
firewall-cmd --permanent --remove-port=Your_Old_Port/tcp

# 重启防火墙
firewall-cmd --reload

# 启动
systemctl start firewalld
# 查看状态
systemctl status firewalld
# 停止
systemctl disable firewalld
# 禁用
systemctl stop firewalld

# 查看版本
firewall-cmd --version
# 查看帮助
firewall-cmd --help
# 显示状态
firewall-cmd --state
# 查看所有打开的端口
firewall-cmd --zone=public --list-ports
# 更新防火墙规则
firewall-cmd --reload
# 查看区域信息
firewall-cmd --get-active-zones
# 查看指定接口所属区域
firewall-cmd --get-zone-of-interface=eth0
# 拒绝所有包
firewall-cmd --panic-on
# 取消拒绝状态
firewall-cmd --panic-off
# 查看是否拒绝
firewall-cmd --query-panic
----

. 使用 SSH 客户端测试新追加的端口能否正常登录，如果没问题了，再将默认端口注释掉：
+
[source]
----
# Port 22
Port Your_New_SSH_Port
----

=== 如何安装JDK？

. 事前准备：
.. FTP软件（例如 FileZilla）
.. JDK包（*.tar.gz）

. JDK一般安装到/usr目录下，创建java文件夹
+
[source]
----

----

== Shadowsocks

. VPS安装
+
选择CentOS 7 x64

. SSH远程登录（默认端口22）

. Shadowsocks安装
+
[source]
----
yum install m2crypto python-setuptools

easy_install pip

pip install shadowsocks
----

. Shadowsocks设置
.. 用vi创建或打开配置文件
+
[source]
----
vi  /etc/shadowsocks.json
----

.. 编辑内容
+
[source]
----
{
    "server": "Your_SS_IP",
    "server_port": Your_SS_Port,
    "local_address": "127.0.0.1",
    "local_port": 1080,
    "password": "Your_Shadowsocks_Password",
    "timeout": 300,
    "method": "aes-256-cfb",
    "fast_open": false
}
----
【I】插入编辑，【Esc】退出编辑，“:q”退出，“:wq”保存退出
+
[NOTE]
====
json文件的内容尽量手动输入，如果从Windows系统中拷贝，有可能带入BOM字符，导致文件解析失败。
====

. <<x_ChangeDefaultSSHPort, 修改SSH默认端口>>

. 防火墙安装
+
[source]
----
yum install firewalld

systemctl start firewalld
----

. <<x_firewall, 防火墙设置>>
+
[source]
----
# 打开SSH端口
firewall-cmd --permanent --zone=public --add-port=Your_SSH_Port/tcp
# 打开SS端口
firewall-cmd --permanent --zone=public --add-port=Your_SS_Port/tcp
# 重载以便生效
firewall-cmd --reload
----

. Shadowsocks启动
+
[source]
----
# 前台运行
ssserver -c /etc/shadowsocks.json

# 或 后台运行
nohup ssserver -c /etc/shadowsocks.json &
----
+
[NOTE]
====
发生问题时应在前台运行，以便输出日志、分析原因。
====

. CentOS更新
+
[source]
----
yum update
----
