= 杂七杂八
:icons:
:toc:
:numbered:

== Windows CMD命令

. DOS路径缩写

.. 如下命令可以查询缩写名：
+
----
dir /x
----

.. 缩写规则：
+
共8位，前6位字符 + "~" + 序号

. 计算HASH值
+
----
certutil -hashfile D:\1.exe MD5
certutil -hashfile D:\1.exe SHA1
certutil -hashfile D:\1.exe SHA256
----

== cmder

. 在右键菜单中添加快捷方式

.. Open a terminal as an Administrator
.. Navigate to the directory you have placed Cmder
.. Execute
+
----
.\cmder.exe /REGISTER ALL
----
+
If you get a message "Access Denied" ensure you are executing the command in an Administrator prompt.

. git log 中文乱码

- 打开 Settings > Startup > Environment，追加一行：
+
----
set LANG=zh_CN.UTF8
----

. 自定义快捷键

- 打开 Settings > Keys&Macro，追加设定：
----
// Split: Duplicate active 'shell' split to right ...
Ctrl + Shift + Right

// Split: Duplicate active 'shell' split to bottom ...
Ctrl + Shift + Down
----

== Fonts for Developers （编程字体）

- *新宋体*
    * 优点
        ** Visual Studio 2013 默认字体，对中文、全角符号的支持较好，字体放大或缩小后仍然等宽。
    * 缺点
        ** 数字0和大写字母O，数字1和小写字母l  的辨识度稍差。

- *MS Gothic*
    * 优缺点参考新宋体。

- *Inziu Iosevka SC / Inziu IosevkaCC SC / ...*
    * 优点
        ** 对中文支持较好，其中后者支持全角符号等宽。数字0和大写字母O，数字1和小写字母l  的辨识度较高。
    * 缺点
        ** 默认的12号字效果较好，但在个别编辑器中（NotePad++），字体放大或缩小后不再等宽。

- *其他字体（包括但不限于：Consolas，Courier，Source Code Pro）*
    * 缺点
        ** 对中文支持不够。

----
'SourceCodePro-Medium', ＭＳ ゴシック, 'MS Gothic', monospace
'Inziu IosevkaCC SC', '新宋体'

// 一二三四五六七八九零一二三四五六七八“”‘’（）【】
// 1234567890123456789012345678901234567890123456789012
// `~!@#$%^&*()_+-={}[]|\:;"'<>,.?/
// abcdefghijklmnopqrstuvwxyz
// ABCDEFGHIJKLMNOPQRSTUVWXYZ
----

== IBM Data Studio v4.1.2

. 安装完成后无法启动，错误日志举例如下：
+
----
!ENTRY org.eclipse.equinox.registry 2 0 2017-02-21 10:31:38.280
!MESSAGE 忽略了捆绑软件“com.ibm.datatools.attributesexplorer.nl1”中的扩展和扩展点。捆绑软件未被标记为单一捆绑软件。
----
+
https://www.ibm.com/developerworks/community/forums/html/topic?id=a29fda4a-5ec8-4380-9400-b03c385a0f70[解决方法参考]

.. 第一回处理
... Entry command line (cmd)
... input Data Studio installation path,for example:
+
----
cd C:\Program Files\IBM\DS4.1.2
----
... input command: 'eclipse.exe -data workspace path',for example:
+
----
eclipse.exe -data C:\yangchaorui_work\Data Studio\workspace_test
----

.. 第二回处理
... cmd
... entry your Data Studio installation path, for example:
+
----
cd C:\Program Files\IBM\DS4.1.2
----
... input 'eclipse -configuration validpath'. For example:
+
----
eclipse -configuration C:\Program Files\IBM\DS4.1.2
----

.. [yellow]*第三回处理*
... Add one line
+
----
-Dequinox.ds.block_timeout=60000
----
at bottom of the file 'eclipse.ini' that located in the 'C:\Program Files\IBM\DS4.1.2'.
... Specify the workspace path without special sign like '#'
... Delete all files(.fileTable.*) which located in the 'C:\Program Files\IBM\DS4.1.2\configuration\org.eclipse.osgi\.manager'.


== IBM i Access Client Solutions 客户端设置

. 键盘映射

.. 新版本中取消了【IBM Default】方案，需要手动修改2项：

... 【Host Functions】-【Enter】 → Control（right）

... 【Host Functions】-【Field Exit】 → Enter 或 Enter（numpad）

.. 完整配置如下（*.kmp）：
+
----
[KeyRemap]
B109=[field-]
B107=[field+]
C33554468=[rule]
C33554467=[backtabword]
C33554466=[tabword]
A33554467=[erinp]
S10=[newline]
C16777233=[reset]
S227=[markright]
C40=[movedown]
S226=[markleft]
S33554587=[dup]
S225=[markdown]
M86=55
S224=[markup]
M84=|271
S127=53
S9=[backtab]
B40=[down]
C33554559=[deleteword]
S123=[pf24]
S122=[pf23]
S121=[pf22]
A40=|293
S120=[pf21]
B33554587=[insert]
XF:[textvisualdisp]=[textvisualdisp]
B155=[insert]
C39=[moveright]
C38=[moveup]
C37=[moveleft]
C155=54
C36=[rule]
C35=[backtabword]
C34=[tabword]
B39=[right]
B38=[up]
B37=[left]
B36=[home]
B35=[eof]
B34=[pagedn]
S119=[pf20]
A39=[tabword]
B33=[pageup]
S118=[pf19]
A38=|296
S117=[pf18]
A37=[backtabword]
C90=|206
S116=[pf17]
XM:C10=C10
S115=[pf16]
A35=[erinp]
XF:[textlogicaldisp]=[textlogicaldisp]
S114=[pf15]
S113=[pf14]
S112=[pf13]
keyVersion=2
D84=|276
C88=53
C87=|272
B27=[attn]
C86=55
M67=54
C84=|271
XM:C33554442=C33554442
C80=|35
S33554468=[fieldmark]
B33554468=[home]
B33554467=[eof]
B33554466=[pagedn]
B33554465=[pageup]
C19=[printhost]
D77=|242
C17=[enter]
D9=|278
B525=|282
B19=[clear]
C77=|26
S33554559=53
S40=[markdown]
A19=[test]
autoApply=false
B10=[fldext]
A227=[tabword]
A226=[backtabword]
A225=|293
A224=|296
S155=[dup]
B227=[right]
B33554559=[delete]
B226=[left]
B225=[down]
C33554587=54
B224=[up]
codePage=1388
C227=[moveright]
B127=[delete]
C226=[moveleft]
C225=[movedown]
C224=[moveup]
B123=[pf12]
B122=[pf11]
C127=[deleteword]
S39=[markright]
B121=[pf10]
S38=[markup]
B120=[pf9]
S37=[markleft]
C9=|277
S36=[fieldmark]
C122=[altcsr]
C67=54
C65=57
S33554442=[newline]
B119=[pf8]
B118=[pf7]
A112=[help]
B117=[pf6]
B116=[pf5]
B115=[pf4]
B114=[pf3]
B113=[pf2]
B112=[pf1]
sessionType=2
C115=|272
B33554442=[fldext]
S27=[sysreq]
B9=[tab]
C114=[altview]
B8=[backspace]
C112=[dspsosi]
----


== JetBrains IDEs

. 常用插件

.. AsciiDoc
.. CodeGlance
.. String Manipulation
.. RegexpTester

== Network

. IPv4地址分类
+
[options="autowidth"]
|===
|类别 |起始地址 |结束地址 |默认子网掩码 |可分配IP数
|A类 |0.0.0.0 |127.255.255.255 |255.0.0.0 |1677万+ ?
|B类 |128.0.0.0 |191.255.255.255 |255.255.0.0 |6万+ ?
|C类 |192.0.0.0 |223.255.255.255 |255.255.255.0 |254（0和255不能用）
|===
+
[NOTE]
====
. 子网掩码转换为二进制后，由一串连续的1和连续的0组成。
====

== Shadowsocks

. VPS安装
+
选择CentOS 7 x64

. SSH远程登录（默认端口：22）

. Shadowsocks安装
+
----
yum install m2crypto python-setuptools

easy_install pip

pip install shadowsocks
----

. Shadowsocks设置
.. 用vi打开配置文件
+
----
vi  /etc/shadowsocks.json
----

.. 编辑内容
+
----
{
    "server":"Your_VPS_IP",
    "server_port":Your_VPS_Port,
    "local_address": "127.0.0.1",
    "local_port":1080,
    "password":"Your_Shadowsocks_Password",
    "timeout":300,
    "method":"aes-256-cfb",
    "fast_open": false
}
----
【I】插入编辑，【Esc】退出编辑，“:q”退出，“:wq”保存退出

. 防火墙安装
+
----
yum install firewalld

systemctl start firewalld
----

. 防火墙设置
+
----
firewall-cmd --permanent --zone=public --add-port=Your_VPS_Port/tcp

firewall-cmd --reload
----

. Shadowsocks启动
+
----
# 前台运行
ssserver -c /etc/shadowsocks.json

# 或 后台运行
nohup ssserver -c /etc/shadowsocks.json &
----

. 修改 SSH 默认端口

.. 使用 vi 修改配置文件 /etc/ssh/sshd_config ，增加新的端口：
+
----
vi /etc/ssh/sshd_config
----
+
按【I】进入编辑模式，作如下修改：
+
----
// 修改前
#Port 22
#AddressFamily any
#ListenAddress 0.0.0.0
#ListenAddress ::

// 修改后
Port 22
Port Your_New_SSH_Port
#AddressFamily any
#ListenAddress 0.0.0.0
#ListenAddress ::
----

.. 重启 SSH 服务
+
----
service sshd restart
----

.. 如果启用了防火墙，需要添加新开的端口：
+
----
// centos 7 默认使用 firewalld ，查看是否运行
firewall-cmd --state

// 查看端口
firewall-cmd --permanent --list-port

// 添加端口
firewall-cmd --permanent --zone=public --add-port=Your_New_SSH_Port/tcp

// 删除端口
firewall-cmd --permanent --remove-port=Your_Old_Port/tcp

// 重启防火墙
firewall-cmd --reload
----

.. 使用 SSH 工具测试新追加的端口能否正常登录，如果没问题了，再把默认端口删除：
+
----
// 修改前
Port 22
Port Your_New_SSH_Port
#AddressFamily any
#ListenAddress 0.0.0.0
#ListenAddress ::

// 修改后
Port Your_New_SSH_Port
#AddressFamily any
#ListenAddress 0.0.0.0
#ListenAddress ::
----

== Sublime Text 3

. 配置
.. 首先需要安装 Package Control（ https://packagecontrol.io/installation[链接]），安装后重启。

.. 公司环境中，需要在【Preferences】-【Package Settings】-【Package Control】-【Settings - User】中添加代理设定：
+
----
"http_proxy": "YourProxy.com:Port",
"https_proxy": "YourProxy.com:Port",
"proxy_username": "YourUsername"
"proxy_password": "YourPassword",
----
+
配置完成后重启。

.. 使用快捷键【ctrl+shift+p】，输入【install package】后执行，再在Packages列表中选择安装。常用的有：
+
----
Alignment
BracketHighlighter
Emmet（注1）
FileDiffs
JsFormat
SideBarEnhancements
----
+
[NOTE]
====
注1：Emmet需要pyv8，代理环境下如果自动安装失败，可以去github下载压缩包，并解压到安装目录。
例如下载的压缩包是 pyv8-win64-p3.zip，则解压为：
----
\Sublime Text 3\Installed Packages\PyV8\pyv8-win64-p3
----
====


. 使用

.. 快捷键
+
在【Preferences】-【Key Bindings】中追加：
+
----
// 自动缩进
{ "keys": ["ctrl+k", "ctrl+d"], "command": "reindent", "args": {"single_line": false} }
----

.. 在右键菜单“Open with Sublime Text”前追加图标
+
安装时如果勾选了“Add to explorer context menu”，安装后在鼠标右键菜单中就会出现“Open with Sublime Text”，但只有文字没有图标。
手动增加图标的方法如下：

... regedit 打开注册表编辑器
... 找到 \HKEY_CLASSES_ROOT\*\shell\Open with Sublime Text\ ，新建一个字符串值，名称为“Icon”，值为主程序的路径（例如：
C:\Program Files\Sublime Text 3\sublime_text.exe）。

== Talend Open Studio for Data Integration 测试记录

. 测试环境

    - Windows Server 2008 R2 64bit 中文标准版
    - 内存4G
    - 硬盘80G
    - server-jre-8u74-windows-x64
    - TOSDI 6.1.1

. 测试对象

    - IBM AS/400 V5R4
    - IBM Lotus Notes 7 Database
    - Microsoft SQL Server 2008 R2
    - Oracle ???

. 准备工作

    - 下载jre，解压后放C盘，注意目录尽量短且不要包含空格。
    - JAVA_HOME、Path环境变量配置。
    - 打开TOSDI，菜单中选 Help -> Install Additional Packages，提前安装缺少的包。（也可以测试的时候再安装）

. 测试过程（略）

. 注意事项

    - Notes相关
        * 机器上必须安装Notes客户端或服务端程序，设计job时必须先使用 tLibraryLoad 组件加载 Notes.jar 。
        * tNotesInput、tNotesOutput、tNotesRunAgent 三个Notes组件可以在TalendExchange中下载，下载后解压到用户自定义的组件文件夹中，并在TOSDI的 Preferences>Talend>Compents 中设定用户组件文件夹的位置，重启TOSDI即可看到新的组件了。
            ** talend_tNotesInput
            ** talend_tNotesOutput
            ** talend_tNotesRunAgent

    - AS/400相关

. 测试结果

+
.表1
|===
|Source |Target |DirectTransfer |Replication |Comments

|AS/400 |MSSQL |OK |? |在源查询中使用“CAST(table1.item1 AS CHAR(nn) CCSID xxx)”可以解决中文乱码问题。
|MSSQL |AS/400 |OK |? |-
|Notes |Notes |OK |OK |-
|===

+
.表2
|===
|Source |SP/Agent call |Comments
|AS/400 |OK |目前没有 tAS400SP 组件，可使用 tJDBCSP 组件替代。
|Notes |OK |按官方示例 tLibraryLoad -> tNotesRunAgent，无法正常运行代理，在两组件之间增加 tNotesInput 后则成功。tNotesInput 可选择不存在的视图或表单，不用输出row，只起构造作用。
|===

. 待续...

== VLC Media Player

. Win10 中文字幕乱码的解决方法：
.. “偏好设置”-“字幕/OSD”里“默认编码”改为“通用，中文（GB18030）”
.. 字体改为Microsoft YaHei UI 或者Microsoft YaHei Light