= Node.js
:icons:
:toc:
:numbered:
:toclevels: 4
:source-highlighter: highlightjs
:highlightjsdir: highlight
:highlightjs-theme: monokai

== Node安装

. Linux (CentOS 7 64bit) 安装

.. 下载 tar 包，并放入相应目录。

.. 解压，例如：
+
[source]
----
tar -xvJf node-v8.11.3-linux-x64.tar.xz
----

.. 生成链接，供全局使用：
+
[source]
----
ln -s /usr/nodejs/node-v8.11.3-linux-x64/bin/node /usr/local/bin/node
ln -s /usr/nodejs/node-v8.11.3-linux-x64/bin/npm /usr/local/bin/npm
----

.. 在任意路径输入如下命令，验证效果：
+
[source]
----
node -v
npm -v
----

== Node基础命令

. 查看安装目录
+
----
where node
----

. 查看版本
+
----
node -v
----

== NPM使用

. 查看帮助
+
----
npm help <command>
----

. 查看版本
+
----
npm -v
----

. 升级
+
----
// Linux
sudo npm install npm -g

// Windows
npm install npm -g

// 淘宝镜像
npm install -g cnpm --registry=https://registry.npm.taobao.org
cnpm install npm -g
----

. 列出模块
+
----
npm list
npm ls
----

. 安装模块
+
----
// 本地安装
npm install <Module Name>

// 全局安装
npm install <Module Name> -g
----

.. 本地安装
... 将安装包放在 ./node_modules 下（运行 npm 命令时所在的目录），如果没有 node_modules 目录，
会在当前执行 npm 命令的目录下生成 node_modules 目录。
... 可以通过 require() 来引入本地安装的包。
+
----
var module = require('moduleName');
----

.. 全局安装
... 将安装包放在 /usr/local 下或者你 node 的安装目录。
... 可以直接在命令行里使用。

. 更新模块
+
----
npm update <Module Name>
----

. 搜索模块
+
----
npm search <Module Name>
----

. 卸载模块
+
----
npm uninstall <Module Name>
----

. 使用 package.json

.. package.json 位于模块的目录下，用于定义包的属性。

.. Package.json 属性说明：

... name - 包名。
... version - 包的版本号。
... description - 包的描述。
... homepage - 包的官网 url 。
... author - 包的作者姓名。
... contributors - 包的其他贡献者姓名。
... dependencies - 依赖包列表。如果依赖包没有安装，npm 会自动将依赖包安装在 node_module 目录下。
... repository - 包代码存放的地方的类型，可以是 git 或 svn，git 可在 Github 上。
... main - main 字段指定了程序的主入口文件，require('moduleName') 就会加载这个文件。这个字段的默认值是模块根目录下面的 index.js。
... keywords - 关键字

== Node-RED

=== Node-RED安装配置

. 更换为淘宝npm源
+
[source]
----
# 修改
npm config set registry https://registry.npm.taobao.org

# 查询
npm config get registry
----

. 安装node-RED
+
在nodejs的bin目录下（否则会少生成几个文件？），执行以下命令：
+
[source]
----
npm install -g --unsafe-perm node-red
----
+
部分资源仍要从github获取，国内网络有时不稳定，可以多试几次。

. 修改防火墙设定
+
[source]
----
# 添加默认的1880端口
firewall-cmd --permanent --zone=public --add-port=1880/tcp

# 重载防火墙
firewall-cmd --reload
----

. 运行node-RED
+
在nodejs的bin目录下，执行以下命令：
+
[source]
----
./node-red
----

. 使用浏览器验证（默认URL为 http://127.0.0.1:1880/ ）


