IBM Notes & Domino
==================
:icons:
:toc:
:numbered:

NotesSQL
--------

. 32位/64位选择
+
驱动程序有32位和64位之分，安装时机器上应有Notes客户端或Domino服务端，并据此进行选择。

.. 目前Notes客户端都是32位的，Domino服务端既有32位的，也有64位的。

. Notes SQL 语句示例

.. SQL关键字统一用大写，表名、字段名等大小写敏感。
+
----
SELECT * FROM MainqViewqAll MainqViewqAll
----

.. 使用表的别名、字段名为特殊保留字时，应使用双引号包裹。
+
----
SELECT "Date", "Week", DateType, Category, Total
FROM "f_ReportD" rd
WHERE "Date" >= 20170101
----

ACL
---

[cols="^.^, ^.^, ^.^, ^.^, ^.^", options="autowidth"]
|===
|权限 |作者 |读者 |写 |读

.9+|管理者/设计者/编辑者
|Y |Y |OK |OK
|Y |N |OK |OK
|N |Y |OK |OK
|N |N |[red-background]#NG# |[red-background]#NG#
|Y |- |OK |OK
|N |- |OK |OK
|- |Y |OK |OK
|- |N |[red-background]#NG# |[red-background]#NG#
|- |- |OK |OK

.9+|作者
|Y |Y |OK |OK
|Y |N |OK |OK
|N |Y |[blue-background]#NG# |OK
|N |N |[red-background]#NG# |[red-background]#NG#
|Y |- |OK |OK
|N |- |[blue-background]#NG# |OK
|- |Y |[blue-background]#NG# |OK
|- |N |[red-background]#NG# |[red-background]#NG#
|- |- |[blue-background]#NG# |OK

.9+|读者
|Y |Y |[blue-background]#NG# |OK
|Y |N |[blue-background]#NG# |OK
|N |Y |[blue-background]#NG# |OK
|N |N |[red-background]#NG# |[red-background]#NG#
|Y |- |[blue-background]#NG# |OK
|N |- |[blue-background]#NG# |OK
|- |Y |[blue-background]#NG# |OK
|- |N |[red-background]#NG# |[red-background]#NG#
|- |- |[blue-background]#NG# |OK

|存放者 |ALL |ALL |[blue-background]#NG# |[blue-background]#NG#

|无访问权限 |ALL |ALL |[blue-background]#NG# |[blue-background]#NG#
|===


XPages
------

. 源代码

.. ${ 开头，表示只在页面载入时计算一次。#{ 开头，表示每次访问时都会被计算。
+
----
propertyName="${<language>:<expression>}"
propertyName="#{<language>:<expression>}"
----

.. MaskConverter
+
[cols="^.^,^.^", options="autowidth"]
|===
|掩码字符 |描述
|# |任何有效小数（使用Character.isDigit）
|' |用来跳过任意特殊格式字符
|U |所有的小写字母映射为大写（使用Character.isLetter）
|L |所有的大写字母映射为小写（使用Character.isLetter）
|A |任何有效的十进制数或字母（使用Character.isDigit和Character.isLetter）
|? |任何一个字母
|* |任何字符
|H |任何有效的十六进制字符（0~9、a~f或A~F）
|===

LC LSX(Lotus Connection LotusScript Extension)
----------------------------------------------

. 示例代码
+
----
%REM
<Connection Type = "odbc2">
	Name			"odbc2"
	IsConnected		True
	IsPooled		False
	Server			""
	Userid			""
	Password		""
	Metadata		""
	MapByName		False
	Writeback		False
	FieldNames		""
	OrderNames		""
	Condition		""
	StampField		""
	BaseStamp		0:00:00
	MaxStamp		0:00:00
	TextFormat		65535
	CharacterSet    "NATIVE"
	Procedure		""
	Owner			""
	AlternateMetadata	False
	ConnectTimeout	0
	RecordLimit		0
%END REM
----

Tips & Tricks (R7)
------------------

. notesItem.Contains(value)，当value为全角字符时，检查失败。
+
可遍历 notesItem 的值，逐个比较是否等于 value 。

. Set notesItem = notesItem.CopyItemToDocument( document, newName$ )，
当 Item 为 RichTextItem 且内容很多时，拷贝可能失败（提示 Item 不存在）。
+
拷贝整个文档，再将不需要的 Item 移除。

. 由外部系统发送的邮件（例如SQL Server的报表订阅），附件格式有时不能被正常处理，附件的名称和格式后缀可能丢失。

.. 无额外处理的，将地址本中该NotesID的收信格式改为“Keep in senders’ format”即可正常收信。

.. 有额外处理、但不需要附件的，可将原文档拷贝到内存中使用。

.. 有额外处理、且需要附件的，应先把附件拆到本地，再重新添付附件，最后删除本地的附件。

... 对SQL Server 2014 报表订阅邮件进行了测试，只要有任何读富文本域的操作，
例如 set item = doc.GetFirstItem(“body”)，重新保存文档后，附件名称和格式即发生异常。


. 在代理中使用LotusScript遍历大量文档时，namgr可能因内存不足（out of memory）发生异常，
进而导致整个Domino服务崩溃。

.. 遍历时使用 Delete doc 删除文档的 reference（注意不是删除文档）。(参考：http://www-10.lotus.com/ldd/nd6forum.nsf/55c38d716d632d9b8525689b005ba1c0/114292faefca69b0852574ec004529a8?OpenDocument&Highlight=0,out,of,memory,agent,delete)

.. 将遍历放在 sub routine 中，sub routine 退出后，内存即得以释放。（参考：http://www-10.lotus.com/ldd/nd6forum.nsf/55c38d716d632d9b8525689b005ba1c0/c4968cfbdb09be2e85256fce0063aa50?OpenDocument）

. Round() 和 @Round
+
----
'原版函数采用“银行家舍入”，重写如下：
Function RoundX(number As Double, places As Integer) As Double

    Dim factor As Double

    factor = 10 ^ places
    RoundX = Sgn(number) * Fix( Abs(number) * factor + 0.5) / factor

End Function
----

. 邮件归档时报错：
+
----
Notes error: This server is not permitted to passthru to the specified server
----
+
解决方法：创建代理，删除"archive profile"
+
----
Dim se  As New NotesSession
Dim db  As NotesDatabase
Dim doc As NotesDocument

Set db = se.CurrentDatabase
Set doc = db.GetProfileDocument("archive profile")

If doc.RemovePermanently(True) = True Then
	Msgbox("The archive profile document is removed!")
Else
	Msgbox("Error!")
End If
----

LEI (Lotus Enterprise Integrator for Domino) 7.0.4 升级 8.5.3 记录
--------------------------------------------------------------

- 系统环境：

    * 升级前：Windows Server 2003 standard (32-bit)

    * 升级后：2008 R2 Standard (64bit), Office 2010

- 问题点：

    . 升级后原来正常的LotusScript代理发生错误，Excel在服务器端无法正常打开，错误代码 213，错误提示如下：
+
----
Microsoft Office Excel cannot access the file 'C:\Temp\test.xlsx'. There are several possible reasons:
• The file name or path does not exist.
• The file is being used by another program.
• The workbook you are trying to save has the same name as a currently open workbook.
----
+
解决方法：在以下目录创建“Desktop”文件夹即可
+
----
// 32-bit
C:\Windows\System32\config\systemprofile\

// 64-bit
C:\Windows\SysWOW64\config\systemprofile\
----
+
http://www-10.lotus.com/ldd/nd85forum.nsf/5f27803bba85d8e285256bf10054620d/ce0a15474733fc888525799e0060392b?OpenDocument[方法来源]
