= IBM Notes & Domino
:icons:
:toc:
:numbered:

== NotesSQL

. 32位/64位选择
+
驱动程序有32位和64位之分，安装时机器上应有Notes客户端或Domino服务端，并据此进行选择。

.. 目前Notes客户端都是32位的，Domino服务端既有32位的，也有64位的。

. Notes SQL 语句示例

.. SQL关键字统一用大写，表名、字段名等大小写敏感。
+
----
SELECT * FROM MainqViewqAll MainqViewqAll
----

.. 使用表的别名、字段名为特殊保留字时，应使用双引号包裹。
+
----
SELECT "Date", "Week", DateType, Category, Total
FROM "f_ReportD" rd
WHERE "Date" >= 20170101
----

== ACL

[cols="^.^, ^.^, ^.^, ^.^, ^.^", options="autowidth"]
|===
|权限 |作者 |读者 |写 |读

.9+|管理者/设计者/编辑者
|Y |Y |OK |OK
|Y |N |OK |OK
|N |Y |OK |OK
|N |N |[red-background]#NG# |[red-background]#NG#
|Y |- |OK |OK
|N |- |OK |OK
|- |Y |OK |OK
|- |N |[red-background]#NG# |[red-background]#NG#
|- |- |OK |OK

.9+|作者
|Y |Y |OK |OK
|Y |N |OK |OK
|N |Y |[blue-background]#NG# |OK
|N |N |[red-background]#NG# |[red-background]#NG#
|Y |- |OK |OK
|N |- |[blue-background]#NG# |OK
|- |Y |[blue-background]#NG# |OK
|- |N |[red-background]#NG# |[red-background]#NG#
|- |- |[blue-background]#NG# |OK

.9+|读者
|Y |Y |[blue-background]#NG# |OK
|Y |N |[blue-background]#NG# |OK
|N |Y |[blue-background]#NG# |OK
|N |N |[red-background]#NG# |[red-background]#NG#
|Y |- |[blue-background]#NG# |OK
|N |- |[blue-background]#NG# |OK
|- |Y |[blue-background]#NG# |OK
|- |N |[red-background]#NG# |[red-background]#NG#
|- |- |[blue-background]#NG# |OK

|存放者 |ALL |ALL |[blue-background]#NG# |[blue-background]#NG#

|无访问权限 |ALL |ALL |[blue-background]#NG# |[blue-background]#NG#
|===


== URL commands for Web applications (v8.5)

https://www.ibm.com/support/knowledgecenter/zh/SSVRGU_8.5.3/com.ibm.designer.domino.main.doc/H_ABOUT_DOMINO_URL_COMMANDS_4332.html[参考]

== The Domino URL command syntax

----
http://Host/DominoObject?Action&Arguments
----

=== URL commands for opening servers, databases, and views

. Redirect
+
----
http://Server/Dummy.nsf?Redirect&Name=notesserver&Id=To=encodedurl

// examples
http://mercury.com/dummy.nsf?Redirect&Name=Mister%2FHankey&Id=0525666D0060ABBF&To=%FAView%3FOpenView
----
+
[NOTE]
If you force a logout using the ?Logout command, you can redirect to another Web site using the &RedirectTo parameter.

. OpenDatabase
+
----
http://Host/__DatabaseReplicaID.nsf?OpenDatabase

// examples
http://www.mercury.com/leads.nsf?OpenDatabase
http://www.mercury.com/sales/discussion.nsf?OpenDatabase
http://www.mercury.com/__852562F3007ABFD6.nsf?OpenDatabase
----

. OpenView
+
----
http://Host/Database/ViewName?OpenView
http://Host/Database/ViewUniversalID?OpenView
http://Host/Database/$defaultview?OpenView

// examples
http://www.mercury.com/leads.nsf/By+Salesperson?OpenView
http://www.mercury.com/leads.nsf/DDC087A8ACE170F8852562F300702264?OpenView
http://www.mercury.com/leads.nsf/$defaultview?OpenView

// Optional arguments for OpenView
Collapse=n
CollapseView
Count=n
Expand=n
ExpandView
RestrictToCategory=category
Start=n
StartKey=string

// examples
http://www.mercury.com/leads.nsf/DDC087A8ACE170F8852562F30070226400000196?OpenView&CollapseView
http://www.mercury.com/leads.nsf/DDC087A8ACE170F8852562F30070226400000196?OpenView&ExpandView
http://www.mercury.com/leads.nsf/By+Category?OpenView&RestrictToCategory=pricing
http://www.mercury.com/leads.nsf/DDC087A8ACE170F8852562F30070226400000196?OpenView&Start=3&Count=15
http://www.mercury.com/leads.nsf/DDC087A8ACE170F8852562F30070226400000196?OpenView&StartKey=F
----

. ReadViewEntries
+
[NOTE]
This command only returns the documents a user is allowed to access.
+
----
http://Host/Database/ViewName?ReadViewEntries
http://Host/Database/ViewUniversalID?ReadViewEntries
http://Host/Database/$defaultview?ReadViewEntries

// examples
http://www.mercury.com/leads.nsf/By+Salesperson?ReadViewEntries
http://www.mercury.com/leads.nsf/DDC087A8ACE170F8852562F300702264?ReadViewEntries
http://www.mercury.com/leads.nsf/$defaultview?ReadViewEntries

// Optional arguments for ReadViewEntries
Collapse=n
CollapseView
Count=n
Endview=1
Expand=n
ExpandView
KeyType=text|time|number
NavigateReverse=1
Outputformat=JSON
PreFormat
ResortAscending=column number
ResortDecending=column number
RestrictToCategory=category
Start=n
StartKey=string
UntilKey=string

// examples
http://www.mercury.com/leads.nsf/DDC087A8ACE170F8852562F30070226400000196?ReadViewEntries&CollapseView
http://www.mercury.com/leads.nsf/By+Category?ReadViewEntries&Endview=1&Count=3
http://www.mercury.com/leads.nsf/DDC087A8ACE170F8852562F30070226400000196?ReadViewEntries&ExpandView
http://www.mercury.com/leads.nsf/By+Category?ReadViewEntries&NavigateReverse=1&Start=50
http://www.mercury.com/leads.nsf/By+Category?ReadViewEntries&outputformat=JSON
http://www.mercury.com/leads.nsf/By+Category?ReadViewEntries&PreFormat
http://www.mercury.com/leads.nsf/By+Category?ReadViewEntries&RestrictToCategory=pricing
http://www.mercury.com/leads.nsf/DDC087A8ACE170F8852562F30070226400000196?ReadViewEntries&Start=3&Count=15
http://www.mercury.com/leads.nsf/DDC087A8ACE170F8852562F30070226400000196?ReadViewEntries&StartKey=F
http://www.mercury.com/leads.nsf/By+Department?ReadViewEntries&StartKey=312&KeyType=number
----

. OpenAbout
+
----
http://Host/Database/$about?OpenAbout

// example
http://www.mercury.com/leads.nsf/$about?OpenAbout
----

. OpenHelp
+
----
http://Host/Database/$help?OpenHelp

// example
http://www.mercury.com/leads.nsf/$help?OpenHelp
----

. OpenIcon
+
----
http://Host/Database/$icon?OpenIcon

// example
http://www.mercury.com/leads.nsf/$icon?OpenIcon
----

=== URL commands for opening framesets

. OpenFrameset
+
----
http://Host/Database/FramesetName?OpenFrameset
http://Host/Database/FramesetUNID?OpenFrameset

// examples
http://www.mercury.com/discussion.nsf/main?OpenFrameset
http://www.mercury.com/discussion.nsf/35AE8FBFA573336A852563D100741784?OpenFrameset
----

=== URL commands for opening agents, forms, and navigators

. OpenAgent
+
----
http://Host/Database/AgentName?OpenAgent

// example
http://www.mercury.com/sales/leads.nsf/Process+New+Leads?OpenAgent
----
+
[NOTE]
Agents may only be referred to by name. The use of UNID is not supported when referring to an agent.

. OpenForm
+
----
http://Host/Database/FormName?OpenForm
http://Host/Database/FormUniversalID?OpenForm
http://Host/Database/$defaultform?OpenForm

// examples
http://www.mercury.com/products.nsf/Product?OpenForm
http://www.mercury.com/products.nsf/625E6111C597A11B852563DD00724CC2?OpenForm
http://www.mercury.com/products.nsf/$defaultform?OpenForm

// Optional argument for OpenForm
ParentUNID = UniqueIDNumber
http://Host/Database/FormUniversalID?OpenForm&ParentUNID

// example
http://www.mercury.com/products.nsf/40aa91d55cle4c8285256363004dc9e0?OpenForm&ParentUNID=6bc72a92613fd6bf852563de001f1a25
----

. OpenNavigator
+
----
http://Host/Database/NavigatorName?OpenNavigator
http://Host/Database/NavigatorUniversalID?OpenNavigator

// examples
http://www.mercury.com/products.nsf/Main+Navigator?OpenNavigator
http://www.mercury.com/products.nsf/7B5BC17C7DC9EB7E85256207004F8862?OpenNavigator
----

. ReadForm
+
----
http://Host/Database/FormName?ReadForm
http://Host/Database/FormUniversalID?ReadForm
http://Host/Database/$defaultform?ReadForm

// examples
http://www.mercury.com/home.nsf/Welcome?ReadForm
http://www.mercury.com/products.nsf/625E6111C597A11B852563DD00724CC2?ReadForm
http://www.mercury.com/products.nsf/$defaultform?ReadForm
----

=== URL commands for opening resources

. OpenImageResource
+
----
http://Host/Database/ImageResourceName?OpenImageResource

// example
http://www.mercury.com/leads.nsf/TopHeader.gif?OpenImageResource
----

. OpenFileResource
+
----
http://Host/Database/FileResourceName?OpenFileResource

// example
http://www.mercury.com/leads.nsf/JSLibrary.js?OpenFileResource
----

=== URL commands for creating, deleting, editing, opening, and saving documents

. CreateDocument
+
----
http://Host/Database/Form?CreateDocument
http://Host/Database/FormName?CreateDocument

// examples
http://www.mercury.com/products.nsf/b9815a87b36a85d9852563df004a9533?CreateDocument
http://www.mercury.com/products.nsf/basketballs?CreateDocument
----

. DeleteDocument
+
----
http://Host/Database/View/Document?DeleteDocument

// example
http://www.mercury.com/products.nsf/By+Part+Number/PC156?DeleteDocument
----

. EditDocument
+
----
http://Host/Database/View/Document?EditDocument

// example
http://www.acme.com/products.nsf/By+Part+Number/PC156?EditDocument
----
+
[NOTE]
Rich text fields containing hidden text will be visible to Web users with Editor access to documents.
+
[NOTE]
=====
The following items may be lost or corrupted if they are in a rich text field which is edited with a Web browser using Domino Web Server:

- embedded images -- may be visible when editing, but will be lost when the document is saved;

- tab tables -- only the visible row will be saved;

- "hide when" paragraphs which are hidden from the Web -- the entire paragraph will be lost when the document is saved.
=====

. OpenDocument
+
----
http://Host/Database/View/Document?OpenDocument

// $first : The first document in the view.

// examples
http://www.mercury.com/products.nsf/By+Part+Number/PC156?OpenDocument
http://www.mercury.com/leads.nsf/By+Rep/35AE8FBFA573336A852563D100741784?OpenDocument
----

. SaveDocument
+
----
http://Host/Database/View/Document?SaveDocument

// example
http://www.mercury.com/products.nsf/a0cefa69d38ad9ed8525631b006582d0/4c95c7c6700160e2852563df0078cfeb?SaveDocument
----

=== URL commands for opening documents by key

. Using Domino URLs to access a document
+
----
http://Host/Database/View/DocumentName?OpenDocument

// example
http://www.mercury.com/register.nsf/Registered+Users/Jay+Street?OpenDocument
http://www.mercury.com/register.nsf/0/466c5172561e1c5c852566c2005f6bbb?OpenDocument
----

. Using @commands to link to a document

. Using Domino URLs to access attachments
+
----
// example
http://domino.lotus.com/domdown.nsf/ViewUNID/DocumentUNID/$File/DOMINO.EXE
----

=== URL commands for opening pages

. OpenPage
+
----
http://Host/Database/PageName?OpenPage
http://Host/Database/PageUNID?OpenPage

// examples
http://www.mercury.com/discussion.nsf/products?OpenPage
http://www.mercury.com/discussion.nsf/35AE8FBFA573336A852563D100741784?OpenPage

// Optional arguments for OpenPage and OpenDocument
CollapseOutline=[n]
ExpandOutline=[n]
StartOutline=[n]

http://Host/Database/PageName?OpenPage&CollapseOutline=n
http://Host/Database/PageUNID?OpenPage&CollapseOutline=n

http://Host/Database/PageName?OpenPage&ExpandOutline=n
http://Host/Database/PageUNID?OpenPage&ExpandOutline=n

http://Host/Database/PageName?OpenPage&StartOutline=n
http://Host/Database/PageUNID?OpenPage&StartOutline=n

// examples
http://www.mercury.com/sales.nsf/products?OpenPage&CollapseOutline=1
http://www.mercury.com/sales.nsf/products?OpenDocument&CollapseOutline=1
http://www.mercury.com/sales.nsf/products?OpenPage&CollapseOutline=1.2.3
http://www.mercury.com/sales.nsf/products?OpenDocument&CollapseOutline=1.2.3

http://www.mercury.com/sales.nsf/products?OpenPage&ExpandOutline=5
http://www.mercury.com/sales.nsf/products?OpenDocument&ExpandOutline=5
http://www.mercury.com/sales.nsf/35AE8FBFA573336A852563D100741784?OpenPage&ExpandOutline=5.1.2
http://www.mercury.com/sales.nsf/35AE8FBFA573336A852563D100741784?OpenDocument&ExpandOutline=5.1.2

http://www.mercury.com/sales.nsf/products?OpenPage&StartOutline=1
http://www.mercury.com/sales.nsf/products?OpenDocument&StartOutline=1
http://www.mercury.com/sales.nsf/35AE8FBFA573336A852563D100741784?OpenPage&StartOutline=5.1.2
http://www.mercury.com/sales.nsf/35AE8FBFA573336A852563D100741784?OpenDocument&StartOutline=5.1.2
----

=== URL commands for opening attachments, image files, and OLE objects

. OpenElement

.. Using OpenElement with attachments
+
----
http://Host/Database/View/Document/$File/Filename?OpenElement

// example
http://www.mercury.com/lproducts.nsf/By+Part+Number/SN156/$File/spec.txt?OpenElement
----
+
[NOTE]
If more than one attached file has the same name, the URL includes both the "internal" file name as well as the external name. Since the internal file name is not easily determined, make sure all attached files have unique names.

.. Using OpenElement with image files
+
----
http://Host/Database/View/Document/FieldName/FieldOffset?OpenElement
http://Host/Database/View/Document/FieldName/FieldOffset?OpenElement&FieldElemFormat=ImageFormat

// Optional argument for OpenElement
FieldElemFormat = ImageFormat
// Where ImageFormat is either .GIF or .JPEG. If you do not specify FieldElemFormat, Domino assumes the image file format is .gif.
----

.. Using OpenElement with OLE Objects
+
----
http://Host/Database/View/Document/FieldName/FieldOffset/$OLEOBJINFO/FieldOffset/obj.ods?OpenElement
----
+
[NOTE]
The current URL syntax for referencing images and objects in Notes documents -- specifically the FieldOffset -- makes it impractical to create these URLs manually. As an alternative, you may paste the actual bitmap or object in place of the reference, create URL references to files stored in the file system, or attach the files to the documents.

=== URL commands for searching for text

. SearchDomain
+
----
http://Host/Database/[templateForm]?SearchDomain[ArgumentList]

// example
http://www.mercury.com/mersrch.nsf/MercuryResults?SearchDomain
----

. SearchSite
+
----
http://Host/Database/[$SearchForm]?SearchSite[ArgumentList]

// example
http://www.mercury.com/mercsrch.nsf/$SearchForm?SearchSite
----

. SearchView
+
----
http://Host/Database/View/[$SearchForm]?SearchView[ArgumentList]

// example
http://www.mercury.com/products.nsf/By+Product+Number/$SearchForm?SearchView

// Optional arguments for SearchSite, SearchView, and SearchDomain
$SearchForm
ArgumentList
Query=string
Count=[n]
Scope=[1,2,3]
SearchEntry=formName
SearchFuzzy=[TRUE,FALSE]

SearchOrder=[1,2,3,4]
// Indicate 1 to "Sort by relevance," 2 to "Sort by date ascending," 3 to "Sort by date descending." The default is 1. SearchView also supports a SearchOrder value of 4 to "Keep current order," which sorts the resulting set of documents in the order in which they appear in the view.
// Specifying SearchOrder=4 will produce unexpected results if:
//  - The Count=n argument is used with a value less than the number of documents found
//  - The Start=n argument is used with a value other than 1
//  - The Default Search Limit is less than the number of documents found
//  - The Max Search Limit is less than the number of documents found
// If you need to specify SearchOrder=4, observe these recommendations:
//  - Never specify Count=n or Start=n
//  - Always specify SearchMax=0
//  - Set the Web site's Max Search Limit to a large value

SearchMax=[n]
SearchWV=[TRUE, FALSE]
Start=[n]

// examples
http://www.mercury.com/mercsrch.nsf/?SearchSite&Query=product+info+requests&SearchOrder=2&SearchMax=30&SearchWV=TRUE&SearchEntry="myResultsForm"
http://www.mercury.com/products.nsf/By+Product+Number/?SearchView&Query=PC156&SearchOrder=3&SearchMax=1&SearchFuzzy=TRUE&SearchWV=FALSE
----

=== Using Next and Previous buttons or hotspots with Start and Count parameters

=== URL commands for required authentication

. Login
+
----
http://Host/DatabaseDirectory/DatabaseFileName?OpenDatabase&login

// example
http://www.mercury.com/sales/leads.nsf?OpenDatabase&login
----

. Logout
+
----
http://Host/DatabaseDirectory/DatabaseFileName?Logout
http://Host/DatabaseDirectory/DatabaseFileName?Logout&RedirectTo

// examples
Http://acmeserver/sessions.nsf?logout&redirectto=http://www.sales.com
----

=== URL commands for processing SSL certificates

. OpenForm with SpecialAction argument
+
----
http://Host/Database/FormName?OpenForm&SpecialAction=specialActionField

// specialActionField is the name of an editable text field on the form whose value contains a predefined command. To use the field with SSL certificates, use one of the following certificate request commands:
//  - "SubmitCert"
//  - "ServerRequest"
//  - "ServerPickup"

// examples
http://www.mercury.com/certs.nsf/UserCertificateRequest?OpenForm&SpecialAction=SubmitCert
http://www.mercury.com/certs.nsf/ServerCertificateRequest?OpenForm&SpecialAction=ServerRequest
http://www.mercury.com/certs.nsf/Certificate?OpenForm&SpecialAction=ServerPickup
----

. Creating an SSL User Certificate
+
----
http://Host/Database/ResultForm?RequestCert&Command=SubmitCert&TranslateForm=TranslationFormName

// example
http://www.mercury.com/certs.nsf/CertificateProcessed?RequestCert&Command=SubmitCert&TranslateForm=Certificate

// Optional and required fields
CommonName
Org
OrgUnit
Locality
State
Country
IssuerCommonName
IssuerOrg
IssuerOrgUnit
IssuerLocality
IssuerState
IssuerCountry
----

. Creating an SSL Server Certificate Request
+
----
http://Host/Database/MessageForm?RequestCert&Command=ServerRequest&TranslateForm=TranslationFormName

// example
http://www.mercury.com/certs.nsf/CertificateProcessed?RequestCert&Command=ServerRequest&TranslateForm=Certificate

// Optional and required fields
CommonName
Org
OrgUnit
Locality
State
Country
----

=== URL commands for setting user preferences in Web applications

. OpenPreferences
+
----
http://Host/$Preferences.nsf?OpenPreferences[&Arguments]

// example
http://www.mercury.com/$Preferences.nsf?OpenPreferences

// Optional argument for OpenPreferences
&PreferenceType=Menu
&PreferenceType=Time Zone
&PreferenceType=Regional
----
+
[NOTE]
Settings a user specifies for OpenPreferences will not override custom settings you specify for a field or view column.

=== Managing multilingual input in a single database

----
http://Host/Database/FormName?OpenForm&charset=[MIME charset name]

// example
http://www.mercury.com/sales.nsf/Summary?OpenForm&charset=Shift_JIS
----

== XPages

. ${ 开头，表示只在页面载入时计算一次。#{ 开头，表示每次访问时都会被计算。
+
----
propertyName="${<language>:<expression>}"
propertyName="#{<language>:<expression>}"
----

. MaskConverter
+
[options="autowidth"]
|===
|掩码字符 |描述
|# |任何有效小数（使用Character.isDigit）
|' |用来跳过任意特殊格式字符
|U |所有的小写字母映射为大写（使用Character.isLetter）
|L |所有的大写字母映射为小写（使用Character.isLetter）
|A |任何有效的十进制数或字母（使用Character.isDigit和Character.isLetter）
|? |任何一个字母
|* |任何字符
|H |任何有效的十六进制字符（0 ~ 9、a ~ f 或 A ~ F）
|===

. Event Handler 属性

.. event
+
事件的名字，它触发了相关联的服务器操作或客户机脚本。

.. execId
+
控件的ID，它是JSF生命周期的部分执行里用到的根分支。

.. execMode
+
事件处理器的执行模式，可设为以下值。

... complete
+
生命周期在完整的控件层次结构里执行（默认）。

... partial
+
生命周期在控件层次的某个分支里执行，该分支由 execId 指定。

.. handlers
+
客户机事件处理器的集合，每个处理器具有以下属性。

... type
+
目前只支持 text/JavaScript

... script
+
执行的客户机脚本

... renderkit
+
如果脚本运行在 Web 里，使用 HTML_BASIC ；如果脚本运行在 Notes Client 里，则使用 HTML_RCP 。

.. loaded
+
布尔值，它表示页面加载时事件处理器是否包含在控件层次结构中。如果希望页面加载时忽略事件处理器，则设置为 false 。默认是 true ，一个使用
该值的场景是：基于应用程序的角色，某个业务逻辑没有应用于特定的用户。

.. navigate
+
布尔值，它表示与事件处理器相关联的事件处理器在处理时是否进行跳转。

.. refreshId
+
控件的ID，当分支需要部分刷新时，它是分支的根节点。

.. refreshMode
+
事件处理器的刷新模式，可取以下值。

... complete
+
刷新整个页面（默认）。

... partial
+
刷新由 refreshId 指定的部分页面。

... norefresh
+
不刷新页面的任何部分。

.. rendered
+
布尔值，它表示事件处理器是否应该呈现为页面的一部分。如果希望页面呈现时忽略事件处理器，设置其值为 false 。

.. save
+
布尔值，它表示当事件处理器执行时是否执行保存操作。设置为 true 可以自动保存页面中的数据源。

.. submit
+
布尔值，它表示当事件和与之关联的事件处理器被触发时，是否提交页面。设置为 true 来提交页面。

.. parameters
+
参数和 名/值 对的集合，它们在执行与之关联的事件处理器时变为可用。

.. action
+
当触发事件处理器时执行的服务器操作。它可以是简单操作、Javascript或Java方法。

.. immediate
+
布尔值，它表示与事件处理器关联的服务器操作应该在 JSF 生命周期的应用请求值阶段之后和输入值被验证之前执行。如果操作引起 XPages 页面跳转
或页面重绘，则剩下的生命周期阶段将不会再执行。

.. onComplete
+
事件处理器触发 AJAX 请求时使用。该属性是在 AJAX 请求执行之后再执行的客户机脚本。

.. onError
+
事件处理器即将触发 AJAX 请求时使用。该属性是在 AJAX 请求执行失败后再执行的客户机脚本。

.. onStart
+
事件处理器即将触发 AJAX 请求时使用。该属性是在 AJAX 请求执行之前而执行的客户机脚本。

.. script
+
与事件处理器相关联的事件触发时执行的客户机脚本。

. 简单操作
+
[options="autowidth"]
|===
|操作 |标签
|更改文档访问方式 |xp:changeDocumentMode
|确认操作 |xp:confirm
|创建响应文档 |xp:createResponse
|删除文档 |xp:deleteDocument
|删除所选文档 |xp:deleteSelectedDocuments
|执行客户机脚本 |xp:executeClientScript
|执行脚本 |xp:executeScript
|修改字段 |xp:modifyField
|打开页面 |xp:openPage
|发布组件属性 |xp:publishValue
|发布视图列 |xp:publishViewColumn
|保存数据源 |xp:save
|保存文档 |xp:saveDocument
|设置组件模式 |xp:setComponentMode
|设置值 |xp:setValue
|操作组 |xp:actionGroup
|===

. XSP 客户机脚本库

.. XSP 属性
... validateAllFields
... lastSubmit
... submitLatency

.. XSP 函数
... alert, error, confirm, prompt
... partialRefreshGet, partialRefreshPost
... publishEvent
... showSection
... findForm, findParentByTag, getElementById
... trim, startsWith, endsWith
... log

== Predefined fields with built-in functionality

. Reserved names for embedded elements
+
[options="autowidth"]
|===
|Reserved field name |Contains
|$GroupScheduleRefreshMode |A value for refreshing an embedded group scheduling control.
|$GroupScheduleShowLegend |A value of 0 or 1. If the value is 0, the color legend does not display. If the value is 1, the color legend does display. The default is 1.
|$$NavigatorBody |An embedded navigator.
|$$ViewBody |An embedded view.
|$$ViewList |An embedded folder pane.
|===

. Reserved fields for use in billing applications
+
[options="autowidth"]
|===
|Reserved field name |Creates a billing record when a user
|$ChargeRead |Opens a document that contains this field.
|$ChargeWrite |Creates, copies, edits, or saves a document that contains this field.
|===

. Reserved fields for general use
+
[options="autowidth"]
|===
|Reserved field name |Use
|Categories |Categorizes documents.
|FolderOptions |Puts new documents in folders.
|HTML |Passes HTML directly to the server.
|SecretEncryptionKeys |Encrypts documents with secret, rather than public, encryption keys.
|$VersionOpt |Controls version tracking for documents.
|$$HTMLHead |Passes HTML information to be hosted within the <HEAD> tag for a document. The passed information might be meta data (using a <META ...> tag) or JavaScript code (using a <SCRIPT ...> tag) or CSS information (using a <STYLE ...> tag).
|$$Return |After Web users submit a document, Domino responds with the default confirmation "Form processed." To override the default response, add a computed text field to the form, name it $$Return, and use HTML as the computed value to create a customized confirmation.
|===

. Reserved names for embedded elements
+
[options="autowidth"]
|===
|Reserved field name |Use
|$Title |When a form is stored in a document, the form name is stored in the internal field named $Title.To use a different form to display the document, create an agent that deletes this stored form information and designates another form to display the document.
|===

. A form as a view or navigator template
+
[options="autowidth"]
|===
|Form name |Design element required and description
|$$ViewTemplate for viewname |Embedded view or $$ViewBody field. Associates the form with a specific view. The form name includes viewname, which is the alias for the view or when no alias exists, the name of the view.
|$$NavigatorTemplate for navigatorname |Embedded navigator or $$NavigatorBody field.

Associates the form with a specific navigator. The form name includes navigatorname, which is the navigator name. For example, the form named "$$NavigatorTemplate for World Map" associates the form with the World Map navigator.

Domino ignores create and read access lists on the form.
|$$ViewTemplateDefault |Embedded view or $$ViewBody field.

Makes this form the template for all Web views that aren't associated with another form.
|$$NavigatorTemplateDefault |Embedded navigator or $$NavigatorBody field.

Makes this form the template for all Web navigators that aren't associated with another form.
|===

. Reserved fields that control mailing options
+
[options="autowidth"]
|===
|Reserved Field name |Values |Comments
|BlindCopyTo |The name(s) of a person, group, or mail-in database. |
|CopyTo |The name(s) of a person, group, or mail-in database. |
|DeliveryPriority |L, N, H |Values correspond to: Low, normal, or high-priority.
|DeliveryReport |N, B, C, T |Values correspond to: None, Only on failure, Confirm delivery, Trace entire path
|Encrypt |1, 0 |Use 1 to encrypt mailed documents.
|MailFormat |B, E, M, T |Enables cc:Mail users to view Notes® documents in a variety of predefined formats:

B = both text and encapsulated.

E = encapsulated in a Notes database, which is attached to the cc:Mail memo.

M = mail. Body field of document is text and pasted into cc:Mail memo.

T = text. Contents of the document are rendered as text and pasted into the body of the cc:Mail memo.
|MailOptions |1, 0 |Use 1 for automatic mailing.
|ReturnReceipt |1, 0 |Use 1 to send a receipt when document is opened by the recipient.
|SaveOptions |1, 0 |Use 1 to save mailed documents. Use 0so that the document is not saved when mailed. prevent the document from being saved.
|SendTo |The name(s) of a person, group, or mail-in database. |Required for all forms that mail documents.
|Sign |1, 0 |Use 1 to an add electronic signature to fields. (Only applicable if a form also contains sign-enabled fields.)
|===

== LC LSX(Lotus Connection LotusScript Extension)

. 示例代码
+
----
%REM
<Connection Type = "odbc2">
	Name			"odbc2"
	IsConnected		True
	IsPooled		False
	Server			""
	Userid			""
	Password		""
	Metadata		""
	MapByName		False
	Writeback		False
	FieldNames		""
	OrderNames		""
	Condition		""
	StampField		""
	BaseStamp		0:00:00
	MaxStamp		0:00:00
	TextFormat		65535
	CharacterSet    "NATIVE"
	Procedure		""
	Owner			""
	AlternateMetadata	False
	ConnectTimeout	0
	RecordLimit		0
%END REM
----

== Tips & Tricks (R7)

. notesItem.Contains(value)，当value为全角字符时，检查失败。
+
可遍历 notesItem 的值，逐个比较是否等于 value 。

. Set notesItem = notesItem.CopyItemToDocument( document, newName$ )，
当 Item 为 RichTextItem 且内容很多时，拷贝可能失败（提示 Item 不存在）。
+
拷贝整个文档，再将不需要的 Item 移除。

. 由外部系统发送的邮件（例如SQL Server的报表订阅），附件格式有时不能被正常处理，附件的名称和格式后缀可能丢失。

.. 无额外处理的，将地址本中该NotesID的收信格式改为“Keep in senders’ format”即可正常收信。

.. 有额外处理、但不需要附件的，可将原文档拷贝到内存中使用。

.. 有额外处理、且需要附件的，应先把附件拆到本地，再重新添付附件，最后删除本地的附件。

... 对SQL Server 2014 报表订阅邮件进行了测试，只要有任何读富文本域的操作，
例如 set item = doc.GetFirstItem(“body”)，重新保存文档后，附件名称和格式即发生异常。


. 在代理中使用LotusScript遍历大量文档时，namgr可能因内存不足（out of memory）发生异常，
进而导致整个Domino服务崩溃。

.. 遍历时使用 Delete doc 删除文档的 reference（注意不是删除文档）。(参考：http://www-10.lotus.com/ldd/nd6forum.nsf/55c38d716d632d9b8525689b005ba1c0/114292faefca69b0852574ec004529a8?OpenDocument&Highlight=0,out,of,memory,agent,delete)

.. 将遍历放在 sub routine 中，sub routine 退出后，内存即得以释放。（参考：http://www-10.lotus.com/ldd/nd6forum.nsf/55c38d716d632d9b8525689b005ba1c0/c4968cfbdb09be2e85256fce0063aa50?OpenDocument）

. Round() 和 @Round
+
----
'原版函数采用“银行家舍入”，重写如下：
Function RoundX(number As Double, places As Integer) As Double

    Dim factor As Double

    factor = 10 ^ places
    RoundX = Sgn(number) * Fix( Abs(number) * factor + 0.5) / factor

End Function
----

. 邮件归档时报错：
+
----
Notes error: This server is not permitted to passthru to the specified server
----
+
解决方法：创建代理，删除"archive profile"
+
----
Dim se  As New NotesSession
Dim db  As NotesDatabase
Dim doc As NotesDocument

Set db = se.CurrentDatabase
Set doc = db.GetProfileDocument("archive profile")

If doc.RemovePermanently(True) = True Then
	Msgbox("The archive profile document is removed!")
Else
	Msgbox("Error!")
End If
----

== LEI (Lotus Enterprise Integrator for Domino) 7.0.4 升级 8.5.3 记录

- 系统环境：

    * 升级前：Windows Server 2003 standard (32-bit)

    * 升级后：2008 R2 Standard (64bit), Office 2010

- 问题点：

    . 升级后原来正常的LotusScript代理发生错误，Excel在服务器端无法正常打开，错误代码 213，错误提示如下：
+
----
Microsoft Office Excel cannot access the file 'C:\Temp\test.xlsx'. There are several possible reasons:
• The file name or path does not exist.
• The file is being used by another program.
• The workbook you are trying to save has the same name as a currently open workbook.
----
+
解决方法：在以下目录创建“Desktop”文件夹即可
+
----
// 32-bit
C:\Windows\System32\config\systemprofile\

// 64-bit
C:\Windows\SysWOW64\config\systemprofile\
----
+
http://www-10.lotus.com/ldd/nd85forum.nsf/5f27803bba85d8e285256bf10054620d/ce0a15474733fc888525799e0060392b?OpenDocument[方法来源]
