Microsoft SQL Server 相关
=======================
:icons:
:toc:
:numbered:

报表服务
-----

----
开发工具：VS2013
----

日期和时间的处理
~~~~~~~~

----
-- 本月第1天
Today.AddDays(1-Today.Day)

-- 本月最后1天
Today.AddDays(1-Today.Day).AddMonths(1).AddDays(-1)

-- 本年第1天
Today.AddMonths(1-Today.month).AddDays(1-Today.day)

-- 本年最后1天
Today.AddDays(1-Today.Day).AddMonths(13-today.month).AddDays(-1)
----

外部引用
~~~~

. 在设计窗口点击报表，顶部菜单会多出2项：【格式】和【报表】。点击【报表】-【报表属性】，可在其中设置外部程序集和类的引用，
或者编写自定义的代码。

. 为了正常生成和预览，自定义的程序集可放在VS安装目录下的【PrivateAssemblies】文件夹中，例如：
C:\Program Files\Microsoft Visual Studio 11.0\Common7\IDE\PrivateAssemblies

. 为了正常部署到服务器，自定义的程序集可放在本地SQL Server安装目录下的【ReportServer】-【bin】文件夹中，例如：
C:\Program Files\Microsoft SQL Server\MSRS12.SSLK01\Reporting Services\ReportServer\bin

报表部署
~~~~

. 在【解决方案资源管理器】视图中，右击报表项目，选择【属性】，可以设置目标服务器的URL和文件夹等。

. 如果不清楚目标服务器的URL，可打开【报表服务配置管理器】，连接到服务器后，在【Web服务URL】中查询确认，一般默认的值为：
http://server:port/ReportServer （端口为80时可省略）

长宽由英寸(inch)转换为厘米(cm)
~~~~~~~~~~~~~~~~~~~~

. 针对手动创建的报表，可在以下路径查找 Report.rdl 模板：
+
----
<Visual_Studio_Install_dir>\Common7\IDE\PrivateAssemblies\ProjectItems\ReportProject
----
+
原内容如下：
+
----
<?xml version="1.0" encoding="utf-8"?>
<Report xmlns="http://schemas.microsoft.com/sqlserver/reporting/2008/01/reportdefinition" xmlns:rd="http://schemas.microsoft.com/SQLServer/reporting/reportdesigner">
	<Width>6.5in</Width>
	<Body>
		<Height>2in</Height>
	</Body>
	<rd:ReportTemplate>true</rd:ReportTemplate>
  <Page>
  </Page>
</Report>
----
+
修改后如下：
+
----
<?xml version="1.0" encoding="utf-8"?>
<Report xmlns="http://schemas.microsoft.com/sqlserver/reporting/2008/01/reportdefinition" xmlns:rd="http://schemas.microsoft.com/SQLServer/reporting/reportdesigner">
	<Width>16.51Cm</Width>
	<Body>
		<Height>5.08Cm</Height>
	</Body>
	<rd:ReportTemplate>true</rd:ReportTemplate>
	<rd:ReportUnitType>Cm</rd:ReportUnitType>
  <Page>
  </Page>
</Report>
----
+
注意：此方法对通过向导创建的报表似乎无效。

原订阅开发者离职，导致订阅日志报错，应如何修改？
~~~~~~~~~~~~~~~~~~~~~~~~

----
DECLARE @OldUserID uniqueidentifier

DECLARE @NewUserID uniqueidentifier

SELECT @OldUserID = UserID FROM dbo.Users WHERE UserName = 'YourDomain\OldUser'

SELECT @NewUserID = UserID FROM dbo.Users WHERE UserName = 'YourDomain\NewUser'

-- UPDATE dbo.Subscriptions SET OwnerID = @NewUserID WHERE OwnerID = @OldUserID

-- select * from dbo.Subscriptions where OwnerID = @OldUserID

SELECT UserName,UserID FROM dbo.Users

select ss.OwnerID,users.UserName,* from Subscriptions as ss LEFT JOIN Users on ss.OwnerID = users.UserID
  ORDER BY ss.OwnerID
----

关于配置无人参与的执行帐户
~~~~~~~~~~~~~

. https://docs.microsoft.com/zh-cn/sql/reporting-services/install-windows/configure-the-unattended-execution-account-ssrs-configuration-manager[参考]
+
[IMPORTANT]
========
配置该帐户的过程为可选操作。 但是，如果不配置该帐户，用于连接到某些数据源的选项会受到限制，并且可能无法从远程计算机检索图像文件。
如果配置了该帐户，则必须对其进行不断更新。 具体来说，如果允许密码过期或在 Active Directory 中更改了帐户信息，则在下次处理报表时
将遇到以下错误：“登录失败 (rsLogonFailed) 登录失败: 未知的用户名或密码不正确。” 即使您从不检索外部图像也不向外部计算机发送连接
请求，正确维护无人参与的报表处理帐户也是必要的。 如果配置了该帐户但后来发现不需要使用它，则可以将其删除以避免日常的帐户维护任务。
========

. 异常举例：
+
执行帐户的密码发生变更，由于反复重试旧密码，导致该帐户被锁定，进而导致报表订阅的邮件无法正常发送。

SQL Server 运维
-------------

主机名或IP地址变更
~~~~~~~~~~

. 变更方法参考 https://msdn.microsoft.com/en-us/library/ms143799%28SQL.100%29.aspx[How to: Rename a Computer that Hosts a Stand-Alone Instance of SQL Server]
+
----
SELECT @@SERVERNAME

sp_dropserver <old_name\instancename>
GO
sp_addserver <new_name\instancename>, local
GO

-- 重启 SQL Server
----

. 域名或IP地址变更后，维护计划中的连接并未更新且无法编辑，可参考如下方法处理（针对由 SQL Server 2005 创建的维护计划）：
http://dba.stackexchange.com/questions/55090/how-to-changes-or-update-local-server-connection-in-maintenance-plan-job[How to changes or update local server connection in Maintenance plan job]
+
----
USE msdb;
DECLARE @oldservername AS VARCHAR(MAX);
SET @oldservername = '<server name>\<instance name>';

SELECT id,CAST(CAST(packagedata AS VARBINARY(MAX)) AS VARCHAR(MAX))
FROM sysssispackages
WHERE(CAST(CAST(packagedata AS VARBINARY(MAX)) AS VARCHAR(MAX)) LIKE '%server='''+@oldservername+'%');
----
+
----
USE msdb;
DECLARE @oldservername AS VARCHAR(MAX);
SET @oldservername = '<server name>\<instance name>';

-- set the new server name to the current server name

DECLARE @newservername AS VARCHAR(MAX);
SET @newservername = @@servername;
DECLARE @xml AS VARCHAR(MAX);
DECLARE @packagedata AS VARBINARY(MAX);

-- get all the plans that have the old server name in their connection string

DECLARE PlansToFix CURSOR
FOR SELECT id
    FROM sysssispackages
    WHERE(CAST(CAST(packagedata AS VARBINARY(MAX)) AS VARCHAR(MAX)) LIKE '%server='''+@oldservername+'%');
OPEN PlansToFix;
DECLARE @planid UNIQUEIDENTIFIER;
FETCH NEXT FROM PlansToFix INTO @planid;
WHILE(@@fetch_status <> -1)  -- for each plan

    BEGIN
        IF(@@fetch_status <> -2)
            BEGIN
                SELECT @xml = CAST(CAST(packagedata AS VARBINARY(MAX)) AS VARCHAR(MAX))
                FROM sysssispackages
                WHERE id = @planid;  -- get the plan's xml converted to an xml string

                DECLARE @planname VARCHAR(MAX);
                SELECT @planname = [name]
                FROM sysssispackages
                WHERE id = @planid;  -- get the plan name
                PRINT 'Changing '+@planname+' server from '+@oldservername+' to '+@newservername;  -- print out what change is happening

                SET @xml = REPLACE(@xml, 'server='''+@oldservername+'''', 'server='''+@newservername+'''');  -- replace the old server name with the new server name in the connection string
                SELECT @packagedata = CAST(@xml AS VARBINARY(MAX));  -- convert the xml back to binary
                UPDATE sysssispackages
                  SET
                      packagedata = @packagedata
                WHERE(id = @planid);  -- update the plan

            END;
        FETCH NEXT FROM PlansToFix INTO @planid;  -- get the next plan

    END;
CLOSE PlansToFix;
DEALLOCATE PlansToFix;
----

. 由 SQL Server 2008 R2 创建的维护计划需要稍微修改一下：
+
----
USE msdb;
DECLARE @oldservername AS VARCHAR(MAX);
SET @oldservername = '<server name>\<instance name>';

SELECT id,CAST(CAST(packagedata AS VARBINARY(MAX)) AS VARCHAR(MAX))
FROM sysssispackages
WHERE(CAST(CAST(packagedata AS VARBINARY(MAX)) AS VARCHAR(MAX)) LIKE '%Data Source='+@oldservername+'%');
----
+
----
USE msdb;
DECLARE @oldservername AS VARCHAR(MAX);
SET @oldservername = '<server name>\<instance name>';

-- set the new server name to the current server name

DECLARE @newservername AS VARCHAR(MAX);
SET @newservername = @@servername;
DECLARE @xml AS VARCHAR(MAX);
DECLARE @packagedata AS VARBINARY(MAX);

-- get all the plans that have the old server name in their connection string

DECLARE PlansToFix CURSOR
FOR SELECT id
    FROM sysssispackages
    WHERE(CAST(CAST(packagedata AS VARBINARY(MAX)) AS VARCHAR(MAX)) LIKE '%Data Source='+@oldservername+'%');
OPEN PlansToFix;
DECLARE @planid UNIQUEIDENTIFIER;
FETCH NEXT FROM PlansToFix INTO @planid;
WHILE(@@fetch_status <> -1)  -- for each plan

    BEGIN
        IF(@@fetch_status <> -2)
            BEGIN
                SELECT @xml = CAST(CAST(packagedata AS VARBINARY(MAX)) AS VARCHAR(MAX))
                FROM sysssispackages
                WHERE id = @planid;  -- get the plan's xml converted to an xml string

                DECLARE @planname VARCHAR(MAX);
                SELECT @planname = [name]
                FROM sysssispackages
                WHERE id = @planid;  -- get the plan name
                PRINT 'Changing '+@planname+' server from '+@oldservername+' to '+@newservername;  -- print out what change is happening

                SET @xml = REPLACE(@xml, 'Data Source='+@oldservername, 'Data Source='+@newservername);  -- replace the old server name with the new server name in the connection string
                SELECT @packagedata = CAST(@xml AS VARBINARY(MAX));  -- convert the xml back to binary
                UPDATE sysssispackages
                  SET
                      packagedata = @packagedata
                WHERE(id = @planid);  -- update the plan

            END;
        FETCH NEXT FROM PlansToFix INTO @planid;  -- get the next plan

    END;
CLOSE PlansToFix;
DEALLOCATE PlansToFix;
----
+
[NOTE]
脚本成功执行后，subplan有可能仍然执行失败，可编辑subplan中的connection，先选中一个临时新建的connection，再选回原来的，保存退出即可。

SQL Server Express
------------------

允许远程管理
~~~~~~

. Express版本默认无法远程连接，需按如下方法配置防火墙规则，重启后即可访问。
https://msdn.microsoft.com/zh-cn/library/ms175043%28v=sql.120%29.aspx[参考]

.. 打开 Windows 防火墙的端口以进行 TCP 访问

... 在“开始”菜单上，单击“运行”，键入 WF.msc，然后单击“确定”。
... 在“高级安全 Windows 防火墙”的左窗格中，右键单击“入站规则”，然后在操作窗格中单击“新建规则”。
... 在“规则类型”对话框中，选择“端口”，然后单击“下一步”。
... 在“协议和端口”对话框中，选择 TCP。 选择“特定本地端口”，然后键入 数据库引擎 实例的端口号，例如默认实例的端口号 1433。 单击“下一步”。
... 在“操作”对话框中，选择“允许连接”，然后单击“下一步”。
... 在“配置文件”对话框中，选择在您想要连接到数据库引擎时描述计算机连接环境的任何配置文件，然后单击“下一步”。
... 在“名称”对话框中，输入此规则的名称和说明，再单击“完成”。

.. 在使用动态端口时打开对 SQL Server 的访问

... 在“开始”菜单上，单击“运行”，键入 WF.msc，然后单击“确定”。
... 在“高级安全 Windows 防火墙”的左窗格中，右键单击“入站规则”，然后在操作窗格中单击“新建规则”。
... 在“规则类型”对话框中，选择“程序”，然后单击“下一步”。
... 在“程序”对话框中，选择“此程序路径”。 单击“浏览”，导航到要通过防火墙访问的 SQL Server 实例，再单击“打开”。 默认情况下，SQL Server 位于 C:\Program Files\Microsoft SQL Server\MSSQL12.MSSQLSERVER\MSSQL\Binn\Sqlservr.exe。 单击“下一步”。
... 在“操作”对话框中，选择“允许连接”，然后单击“下一步”。
... 在“配置文件”对话框中，选择在您想要连接到数据库引擎时描述计算机连接环境的任何配置文件，然后单击“下一步”。
... 在“名称”对话框中，输入此规则的名称和说明，再单击“完成”。
