XML
===
:icons:
:toc:
:numbered:

XML语法
-----

. XML 标签对大小写敏感

. 实体引用
+
在 XML 中，只有字符 "<" 和 "&" 确实是非法的。大于号合法，但是用实体引用来代替它是一个好习惯。
+
----
&lt;     <   小于
&gt;     >   大于
&amp;    &   和号
&apos;   '   单引号
&quot;   "   引号
----

. XML 中的注释
+
在 XML 中编写注释的语法与 HTML 的语法相似：
+
----
<!-- This is a comment -->
----

. 在 XML 中，空格会被保留
+
HTML 会把多个连续的空格字符裁减（合并）为一个：
+
----
HTML:	Hello           my name is David.
输出:	Hello my name is David.
----
+
在 XML 中，文档中的空格不会被删节。

. XML 以 LF 存储换行
+
在 Windows 应用程序中，换行通常以一对字符来存储：回车符 (CR) 和换行符 (LF)。这对字符与打字机设置新行的动作有相似之处。
在 Unix 应用程序中，新行以 LF 字符存储。
而 Macintosh 应用程序使用 CR 来存储新行。

XML元素
-----

. XML 命名规则
.. 名称可以含字母、数字以及其他的字符
.. 名称不能以数字或者标点符号开始
.. 名称不能以字符 “xml”（或者 XML、Xml）开始
.. 名称不能包含空格

+
可使用任何名称，没有保留的字词。


. 最佳命名习惯

.. 使名称具有描述性。使用下划线的名称也很不错。
+
名称应当比较简短，比如：<book_title>，而不是：<the_title_of_the_book>。

.. 避免 "-" 字符。
+
如果您按照这样的方式进行命名："first-name"，一些软件会认为你需要提取第一个单词。

.. 避免 "." 字符。
+
如果您按照这样的方式进行命名："first.name"，一些软件会认为 "name" 是对象 "first" 的属性。

.. 避免 ":" 字符。
+
冒号会被转换为命名空间来使用。

.. XML 文档经常有一个对应的数据库，其中的字段会对应 XML 文档中的元素。有一个实用的经验，即使用数据库的名称规则来命名 XML 文档中的元素。

.. 非英语的字母比如 éòá 也是合法的 XML 元素名，不过需要留意当软件开发商不支持这些字符时可能出现的问题。

XML属性
-----

. XML 元素 vs. 属性，对比以下3例：

.. date属性
+
----
<note date="08/08/2008">
    <to>George</to>
    <from>John</from>
    <heading>Reminder</heading>
    <body>Don't forget the meeting!</body>
</note>
----

.. date元素
+
----
<note>
    <date>08/08/2008</date>
    <to>George</to>
    <from>John</from>
    <heading>Reminder</heading>
    <body>Don't forget the meeting!</body>
</note>
----

.. 扩展date元素
+
----
<note>
    <date>
        <day>08</day>
        <month>08</month>
        <year>2008</year>
    </date>
    <to>George</to>
    <from>John</from>
    <heading>Reminder</heading>
    <body>Don't forget the meeting!</body>
</note>
----

. 避免 XML 属性
+
因使用属性而引起的一些问题：

- 属性无法包含多重的值（元素可以）
- 属性无法描述树结构（元素可以）
- 属性不易扩展（为未来的变化）
- 属性难以阅读和维护

+
尽量使用元素来描述数据。而仅仅使用属性来提供与数据无关的信息。

. 针对元数据的 XML 属性
+
有时候会向元素分配 ID 引用。这些 ID 索引可用于标识 XML 元素，它起作用的方式与 HTML 中 ID 属性是一样的。
+
----
<messages>
    <note id="501">
        <to>George</to>
        <from>John</from>
        <heading>Reminder</heading>
        <body>Don't forget the meeting!</body>
    </note>
    <note id="502">
        <to>John</to>
        <from>George</from>
        <heading>Re: Reminder</heading>
        <body>I will not</body>
    </note>
</messages>
----
+
上面的 ID 仅仅是一个标识符，用于标识不同的便签。它并不是便签数据的组成部分。
+
[NOTE]
====
元数据（有关数据的数据）应当存储为属性，而数据本身应当存储为元素。
====

XML验证
-----

. 验证 XML 文档
+
合法的 XML 文档是“形式良好”的 XML 文档，同样遵守文档类型定义 (DTD) 的语法规则：
+
----
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE note SYSTEM "Note.dtd">
<note>
    <to>George</to>
    <from>John</from>
    <heading>Reminder</heading>
    <body>Don't forget the meeting!</body>
</note>
----

. XML DTD
+
DTD 的作用是定义 XML 文档的结构。它使用一系列合法的元素来定义文档结构：
+
----
<!DOCTYPE note [
        <!ELEMENT note (to,from,heading,body)>
        <!ELEMENT to      (#PCDATA)>
        <!ELEMENT from    (#PCDATA)>
        <!ELEMENT heading (#PCDATA)>
        <!ELEMENT body    (#PCDATA)>
        ]>
----

. XML Schema
+
W3C 支持一种基于 XML 的 DTD 代替者，它名为 XML Schema：
+
----
<xs:element name="note">

    <xs:complexType>
        <xs:sequence>
            <xs:element name="to"      type="xs:string"/>
            <xs:element name="from"    type="xs:string"/>
            <xs:element name="heading" type="xs:string"/>
            <xs:element name="body"    type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

</xs:element>
----



