XML
===
:icons:
:toc:
:numbered:

XML 语法
------

. XML 标签对大小写敏感

. 实体引用
+
在 XML 中，只有字符 "<" 和 "&" 确实是非法的。大于号合法，但是用实体引用来代替它是一个好习惯。
+
----
&lt;     <   小于
&gt;     >   大于
&amp;    &   和号
&apos;   '   单引号
&quot;   "   引号
----

. XML 中的注释
+
在 XML 中编写注释的语法与 HTML 的语法相似：
+
----
<!-- This is a comment -->
----

. 在 XML 中，空格会被保留
+
HTML 会把多个连续的空格字符裁减（合并）为一个：
+
----
HTML:	Hello           my name is David.
输出:	Hello my name is David.
----
+
在 XML 中，文档中的空格不会被删节。

. XML 以 LF 存储换行
+
在 Windows 应用程序中，换行通常以一对字符来存储：回车符 (CR) 和换行符 (LF)。这对字符与打字机设置新行的动作有相似之处。
在 Unix 应用程序中，新行以 LF 字符存储。
而 Macintosh 应用程序使用 CR 来存储新行。

XML 元素
------

. XML 命名规则
.. 名称可以含字母、数字以及其他的字符
.. 名称不能以数字或者标点符号开始
.. 名称不能以字符 “xml”（或者 XML、Xml）开始
.. 名称不能包含空格

+
可使用任何名称，没有保留的字词。


. 最佳命名习惯

.. 使名称具有描述性。使用下划线的名称也很不错。
+
名称应当比较简短，比如：<book_title>，而不是：<the_title_of_the_book>。

.. 避免 "-" 字符。
+
如果您按照这样的方式进行命名："first-name"，一些软件会认为你需要提取第一个单词。

.. 避免 "." 字符。
+
如果您按照这样的方式进行命名："first.name"，一些软件会认为 "name" 是对象 "first" 的属性。

.. 避免 ":" 字符。
+
冒号会被转换为命名空间来使用。

.. XML 文档经常有一个对应的数据库，其中的字段会对应 XML 文档中的元素。有一个实用的经验，即使用数据库的名称规则来命名 XML 文档中的元素。

.. 非英语的字母比如 éòá 也是合法的 XML 元素名，不过需要留意当软件开发商不支持这些字符时可能出现的问题。

XML 属性
------

. XML 元素 vs. 属性，对比以下3例：

.. date属性
+
----
<note date="08/08/2008">
    <to>George</to>
    <from>John</from>
    <heading>Reminder</heading>
    <body>Don't forget the meeting!</body>
</note>
----

.. date元素
+
----
<note>
    <date>08/08/2008</date>
    <to>George</to>
    <from>John</from>
    <heading>Reminder</heading>
    <body>Don't forget the meeting!</body>
</note>
----

.. 扩展date元素
+
----
<note>
    <date>
        <day>08</day>
        <month>08</month>
        <year>2008</year>
    </date>
    <to>George</to>
    <from>John</from>
    <heading>Reminder</heading>
    <body>Don't forget the meeting!</body>
</note>
----

. 避免 XML 属性
+
因使用属性而引起的一些问题：

- 属性无法包含多重的值（元素可以）
- 属性无法描述树结构（元素可以）
- 属性不易扩展（为未来的变化）
- 属性难以阅读和维护

+
尽量使用元素来描述数据。而仅仅使用属性来提供与数据无关的信息。

. 针对元数据的 XML 属性
+
有时候会向元素分配 ID 引用。这些 ID 索引可用于标识 XML 元素，它起作用的方式与 HTML 中 ID 属性是一样的。
+
----
<messages>
    <note id="501">
        <to>George</to>
        <from>John</from>
        <heading>Reminder</heading>
        <body>Don't forget the meeting!</body>
    </note>
    <note id="502">
        <to>John</to>
        <from>George</from>
        <heading>Re: Reminder</heading>
        <body>I will not</body>
    </note>
</messages>
----
+
上面的 ID 仅仅是一个标识符，用于标识不同的便签。它并不是便签数据的组成部分。
+
[NOTE]
====
元数据（有关数据的数据）应当存储为属性，而数据本身应当存储为元素。
====

XML 验证
------

. 验证 XML 文档
+
合法的 XML 文档是“形式良好”的 XML 文档，同样遵守文档类型定义 (DTD) 的语法规则：
+
----
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE note SYSTEM "Note.dtd">
<note>
    <to>George</to>
    <from>John</from>
    <heading>Reminder</heading>
    <body>Don't forget the meeting!</body>
</note>
----

. XML DTD
+
DTD 的作用是定义 XML 文档的结构。它使用一系列合法的元素来定义文档结构：
+
----
<!DOCTYPE note [
        <!ELEMENT note (to,from,heading,body)>
        <!ELEMENT to      (#PCDATA)>
        <!ELEMENT from    (#PCDATA)>
        <!ELEMENT heading (#PCDATA)>
        <!ELEMENT body    (#PCDATA)>
        ]>
----

. XML Schema
+
W3C 支持一种基于 XML 的 DTD 代替者，它名为 XML Schema：
+
----
<xs:element name="note">

    <xs:complexType>
        <xs:sequence>
            <xs:element name="to"      type="xs:string"/>
            <xs:element name="from"    type="xs:string"/>
            <xs:element name="heading" type="xs:string"/>
            <xs:element name="body"    type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

</xs:element>
----

XML CSS
-------

. 举例：
+
----
<?xml version="1.0" encoding="ISO-8859-1"?>
<?xml-stylesheet type="text/css" href="cd_catalog.css"?>
<CATALOG>
    <CD>
        <TITLE>Empire Burlesque</TITLE>
        <ARTIST>Bob Dylan</ARTIST>
        <COUNTRY>USA</COUNTRY>
        <COMPANY>Columbia</COMPANY>
        <PRICE>10.90</PRICE>
        <YEAR>1985</YEAR>
    </CD>
    <CD>
        <TITLE>Hide your heart</TITLE>
        <ARTIST>Bonnie Tyler</ARTIST>
        <COUNTRY>UK</COUNTRY>
        <COMPANY>CBS Records</COMPANY>
        <PRICE>9.90</PRICE>
        <YEAR>1988</YEAR>
    </CD>
    .
    .
    .
    .
</CATALOG>
----
+
[NOTE]
======
使用 CSS 格式化 XML 不是常用的方法，W3C 推荐使用 XSLT。
======

XML XSLT
--------

. XSLT (eXtensible Stylesheet Language Transformations) 是首选的 XML 样式表语言。
+
----
<?xml version="1.0" encoding="ISO-8859-1"?>
<?xml-stylesheet type="text/xsl" href="simple.xsl"?>
<breakfast_menu>
    <food>
        <name>Belgian Waffles</name>
        <price>$5.95</price>
        <description>
            two of our famous Belgian Waffles
        </description>
        <calories>650</calories>
    </food>
</breakfast_menu>
----

XMLHttpRequest 对象
-----------------

----
// 创建 XMLHttpRequest 对象的语法：
xmlhttp=new XMLHttpRequest();

// 老版本的 Internet Explorer （IE5 和 IE6）使用 ActiveX 对象：
xmlhttp=new ActiveXObject("Microsoft.XMLHTTP");
----

XML DOM
-------

. 获取元素的值
+
下面的代码检索第一个 <title> 元素的文本值：
+
----
x=xmlDoc.getElementsByTagName("title")[0].childNodes[0];
txt=x.nodeValue;
----

. 获取属性的值
+
下面的代码检索第一个 <title> 元素的 "lang" 属性的文本值：
+
----
txt=xmlDoc.getElementsByTagName("title")[0].getAttribute("lang");
----

. 改变元素的值
+
下面的代码改变第一个 <title> 元素的文本值：
+
----
x=xmlDoc.getElementsByTagName("title")[0].childNodes[0];
x.nodeValue="Easy Cooking";
----

. 改变属性的值
+
setAttribute() 方法可用于改变已有属性的值，或创建一个新属性。
+
下面的代码向每个 <book> 元素添加了名为 "edition" 的新属性（值是 "first"）：
+
----
x = xmlDoc.getElementsByTagName("book");

for (i = 0; i < x.length; i++) {
    x[i].setAttribute("edition", "first");
}
----

. 创建元素
+
如需创建带有文本内容的新元素，需要同时创建元素节点和文本节点。
+
下面的代码创建了一个元素 (<edition>)，然后把它添加到第一个 <book> 元素中：
+
----
// 创建 <edition> 元素
newel=xmlDoc.createElement("edition");

// 创建值为 "First" 的文本节点
newtext=xmlDoc.createTextNode("First");

// 把这个文本节点追加到 <edition> 元素
newel.appendChild(newtext);

// 把 <edition> 元素追加到第一个 <book> 元素
x=xmlDoc.getElementsByTagName("book");
x[0].appendChild(newel);
----

. 删除元素
+
下面的代码片段将删除第一个 <book> 元素中的第一个节点：
+
----
x=xmlDoc.getElementsByTagName("book")[0];
x.removeChild(x.childNodes[0]);
----
+
注：上例的结果可能会根据所用的浏览器而不同。Firefox 把新行字符当作空的文本节点，而 Internet Explorer 不是这样。


XML 命名空间
--------

. XML 命名空间属性被放置于元素的开始标签之中，并使用以下的语法：
+
----
xmlns:namespace-prefix="namespaceURI"
----
+
当命名空间被定义在元素的开始标签中时，所有带有相同前缀的子元素都会与同一个命名空间相关联。
+
注释：用于标示命名空间的地址不会被解析器用于查找信息。其惟一的作用是赋予命名空间一个惟一的名称。
不过，很多公司常常会作为指针来使用命名空间指向实际存在的网页，这个网页包含关于命名空间的信息。

. 默认的命名空间（Default Namespaces）
+
----
xmlns="namespaceURI"
----

XML CDATA
---------

. 所有 XML 文档中的文本均会被解析器解析。只有 CDATA 段中的文本会被解析器忽略。

. 某些文本，比如 JavaScript 代码，包含大量 "<" 或 "&" 字符。为了避免错误，可以将脚本代码定义为 CDATA。

. CDATA 部分由 "<![CDATA[" 开始，由 "]]>" 结束：
+
----
<script>
    <![CDATA[
function matchwo(a,b)
{
if (a < b && a < 0) then
  {
  return 1;
  }
else
  {
  return 0;
  }
}
]]>
</script>
----

. CDATA 部分不能包含字符串 "]]>"，也不允许嵌套。

. 标记 CDATA 部分结尾的 "]]>" 不能包含空格或折行。

XML 编码
------

. XML 文档可以包含非 ASCII 字符，比如法语。为了避免错误，需要规定 XML 编码，或者将 XML 文档存为 Unicode。

XML 注意事项
--------

. 使用 XML 时应该尽量避免使用：

.. Internet Explorer - XML 数据岛
... 数据岛（XML Data Islands）是嵌入 HTML 页面中的 XML 数据。
... XML 数据岛只在 Internet Explorer 浏览器中有效。
... 应当在 HTML 中使用 JavaScript 和 XML DOM 来解析并显示 XML。

.. Internet Explorer - 行为（behaviors）
... Internet Explorer 5 引入了行为（behaviors）。Behaviors 是通过使用 CSS 样式向 XML （或 HTML ）元素添加行为的一种方法。
... 只有 Internet Explorer 支持 behavior 属性。
... 使用 JavaScript 和 XML DOM （或 HTML DOM）来代替它。

XPath
-----

. XPath 节点
+
有七种类型的节点：元素、属性、文本、命名空间、处理指令、注释以及文档（根）节点。

. XPath 语法
+
XPath 使用路径表达式来选取 XML 文档中的节点或节点集。节点是通过沿着路径 (path) 或者步 (steps) 来选取的。
+
----
<?xml version="1.0" encoding="ISO-8859-1"?>

<bookstore>

    <book>
        <title lang="eng">Harry Potter</title>
        <price>29.99</price>
    </book>

    <book>
        <title lang="eng">Learning XML</title>
        <price>39.95</price>
    </book>

</bookstore>
----

.. 选取节点

... 常用路径表达式
+
[options="autowidth"]
|===
|表达式 |描述
|nodename |选取此节点的所有子节点。
|/ |从根节点选取。
|// |从匹配选择的当前节点选择文档中的节点，而不考虑它们的位置。
|. |选取当前节点。
|.. |选取当前节点的父节点。
|@ |选取属性。
|===
+
绝对路径起始于正斜杠( / )
+
----
// 绝对位置路径
/step/step/...

// 相对位置路径
step/step/...
----

... 实例
+
[options="autowidth"]
|===
|路径表达式 |结果
|bookstore |选取 bookstore 元素的所有子节点。
|/bookstore |选取根元素 bookstore。
注释：假如路径起始于正斜杠( / )，则此路径始终代表到某元素的绝对路径！
|bookstore/book |选取属于 bookstore 的子元素的所有 book 元素。
|//book |选取所有 book 子元素，而不管它们在文档中的位置。
|bookstore//book |选择属于 bookstore 元素的后代的所有 book 元素，而不管它们位于 bookstore 之下的什么位置。
|//@lang |选取名为 lang 的所有属性。
|===

.. 谓语（Predicates）

... 谓语用来查找某个特定的节点或者包含某个指定的值的节点。谓语被嵌在方括号中。

... 实例
+
[options="autowidth"]
|===
|路径表达式 |结果
|/bookstore/book[1] |选取属于 bookstore 子元素的第一个 book 元素。
|/bookstore/book[last()] |选取属于 bookstore 子元素的最后一个 book 元素。
|/bookstore/book[last()-1] |选取属于 bookstore 子元素的倒数第二个 book 元素。
|/bookstore/book[position()<3] |选取最前面的两个属于 bookstore 元素的子元素的 book 元素。
|//title[@lang] |选取所有拥有名为 lang 的属性的 title 元素。
|//title[@lang=\'eng'] |选取所有 title 元素，且这些元素拥有值为 eng 的 lang 属性。
|/bookstore/book[price>35.00] |选取 bookstore 元素的所有 book 元素，且其中的 price 元素的值须大于 35.00。
|/bookstore/book[price>35.00]/title |选取 bookstore 元素中的 book 元素的所有 title 元素，且其中的 price 元素的值须大于 35.00。
|===

.. 选取未知节点

... XPath 通配符可用来选取未知的 XML 元素。
+
[options="autowidth"]
|===
|通配符 |描述
|* |匹配任何元素节点。
|@* |匹配任何属性节点。
|node() |匹配任何类型的节点。
|===

... 实例
+
[options="autowidth"]
|===
|路径表达式 |结果
|/bookstore/* |选取 bookstore 元素的所有子元素。
|//* |选取文档中的所有元素。
|//title[@*] |选取所有带有属性的 title 元素。
|===

.. 选取若干路径

... 通过在路径表达式中使用“|”运算符，您可以选取若干个路径。

... 实例
+
[options="autowidth"]
|===
|路径表达式 |结果
|//book/title \| //book/price |选取 book 元素的所有 title 和 price 元素。
|//title \| //price |选取文档中的所有 title 和 price 元素。
|/bookstore/book/title \| //price |选取属于 bookstore 元素的 book 元素的所有 title 元素，以及文档中所有的 price 元素。
|===

. XPath 轴
+
[options="autowidth"]
|===
|轴名称 |结果
|ancestor |选取当前节点的所有先辈（父、祖父等）。
|ancestor-or-self |选取当前节点的所有先辈（父、祖父等）以及当前节点本身。
|attribute |选取当前节点的所有属性。
|child |选取当前节点的所有子元素。
|descendant |选取当前节点的所有后代元素（子、孙等）。
|descendant-or-self |选取当前节点的所有后代元素（子、孙等）以及当前节点本身。
|following |选取文档中当前节点的结束标签之后的所有节点。
|namespace |选取当前节点的所有命名空间节点。
|parent |选取当前节点的父节点。
|preceding |选取文档中当前节点的开始标签之前的所有节点。
|preceding-sibling |选取当前节点之前的所有同级节点。
|self |选取当前节点。
|===

. XPath 步

.. 步（step）包括：

... 轴（axis）
+
定义所选节点与当前节点之间的树关系

... 节点测试（node-test）
+
识别某个轴内部的节点

... 零个或者更多谓语（predicate）
+
更深入地提炼所选的节点集

.. 步的语法：
+
----
轴名称::节点测试[谓语]
----
+
[options="autowidth"]
|===
|例子 |结果
|child::book |选取所有属于当前节点的子元素的 book 节点。
|attribute::lang |选取当前节点的 lang 属性。
|child::* |选取当前节点的所有子元素。
|attribute::* |选取当前节点的所有属性。
|child::text() |选取当前节点的所有文本子节点。
|child::node() |选取当前节点的所有子节点。
|descendant::book |选取当前节点的所有 book 后代。
|ancestor::book |选择当前节点的所有 book 先辈。
|ancestor-or-self::book |选取当前节点的所有 book 先辈以及当前节点（如果此节点是 book 节点）
|child::*/child::price |选取当前节点的所有 price 孙节点。
|===

. XPath 运算符
+
XPath 表达式可返回节点集、字符串、逻辑值以及数字。

+
[options="autowidth"]
|===
|运算符 |描述 |实例 |返回值
|\| |计算两个节点集 |//book \| //cd |返回所有拥有 book 和 cd 元素的节点集
|+ |加法 |6 + 4 |10
|- |减法 |6 - 4 |2
|* |乘法 |6 * 4 |24
|div |除法 |8 div 4 |2
|= |等于 |price=9.80 |返回 true 或 false
|!= |不等于 |price!=9.80 |返回 true 或 false
|< |小于 |price<9.80 |返回 true 或 false
|<= |小于或等于 |price<=9.80 |返回 true 或 false
|> |大于 |price>9.80 |返回 true 或 false
|>= |大于或等于 |price>=9.80 |返回 true 或 false
|or |或 |price=9.80 or price=9.70 |返回 true 或 false
|and |与 |price>9.00 and price<9.90 |返回 true 或 false
|mod |计算除法的余数 |5 mod 2 |1
|===

. XPath 函数
+
...